### ISSUE TITLE
Error saving task when classmethod named parse_session exists in namespace

### ISSUE THREAD

**Issue by guidj** [spotify/luigi#1017]
# Problem

I have a class Worker, with a class method named `parse_session`:

``` python
class Worker(object):

    @classmethod
    def parse_data(cls, data):
         ...
         for line in data:
             parse_session(line)  #calls parse session

    @classmethod
    def parse_session(cls, line):
        ...
```

I call the method `parse_data`, which in turn calls `parse_session` from a luigi.Task instance:

``` python
class TaskX(luigi.Task):
    def run(self):

        Worker.parse_data(some_data)
```

When I run this task, the job executes, but I get the following error from `luigid`:

```
2015-06-25 17:01:18,184 luigi.server[50463] WARNING: Error saving Task history
Traceback (most recent call last):
  File "/Users/user/code/app/app-env/lib/python3.4/site-packages/luigi/scheduler.py", line 943, in _update_task_history
    self._task_history.task_started(task_id, host)
  File "/Users/user/code/app/app-env/lib/python3.4/site-packages/luigi/db_task_history.py", line 95, in task_started
    self._add_task_event(task, TaskEvent(event_name=RUNNING, ts=datetime.datetime.now()))
  File "/Users/user/code/app/app-env/lib/python3.4/site-packages/luigi/db_task_history.py", line 108, in _add_task_event
    for (task_record, session) in self._find_or_create_task(task):
  File "/Users/user/code/app/app-env/lib/python3.4/site-packages/luigi/db_task_history.py", line 122, in _find_or_create_task
    task_record.parameters[k] = TaskParameter(name=k, value=v)
  File "/Users/user/code/app/app-env/lib/python3.4/site-packages/sqlalchemy/orm/collections.py", line 1225, in __setitem__
    value = __set(self, value, _sa_initiator)
  File "/Users/user/code/app/app-env/lib/python3.4/site-packages/sqlalchemy/orm/collections.py", line 1044, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/Users/user/code/app/app-env/lib/python3.4/site-packages/sqlalchemy/orm/collections.py", line 716, in fire_append_event
    item, initiator)
  File "/Users/user/code/app/app-env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 936, in fire_append_event
    initiator or self._append_token or self._init_append_token())
  File "/Users/user/code/app/app-env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 36, in append
    sess = state.session
AttributeError: 'InstanceState' object has no attribute 'parse_session'
```
# Resolution

Changing `parse_session` to something else stops the error from occurring. 
Any ideas of why this is happening? Thanks
# System

OS: OSX 10.10
Python: 3.4.3
luigi: 1.2.1

**Comment by erikbern** [comment]
Super weird. No idea what's going on. I don't understand why it's failing because the last line in the traceback says "sess = state.sesssion" not parse_session

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [x] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [x] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
