### ISSUE TITLE
hadoop streaming stuck on 0%

### ISSUE THREAD

**Issue by endeavorchan** [spotify/luigi#1102]
Hi,
I got the hadoop to run, but there is another problem. 
the job is is suck on 0%.

INFO: 15/07/30 11:01:52 INFO mapred.JobClient: Total split num: 1
INFO: 15/07/30 11:01:52 INFO mapred.JobClient: Total split size: 288 (bytes)
INFO: 15/07/30 11:01:52 INFO mapred.JobClient: Total split time: 1930 (ms)
INFO: 15/07/30 11:01:53 INFO mapred.JobClient:  map 0% reduce 0%
INFO: 15/07/30 11:02:50 INFO mapred.JobClient: Updating completed job! Ignoring ...
INFO: 15/07/30 11:02:50 INFO mapred.JobClient: Updating completed job! Ignoring ...
INFO: 15/07/30 11:02:50 ERROR mapred.JobClient: Job not Successful!
INFO: Streaming Job Failed!

and there is an exception with code 143:

java.io.IOException: hce child exception : subprocess exited with code 143
	at org.apache.hadoop.mapred.hce.Application.abort(Application.java:881)
	at org.apache.hadoop.mapred.hce.HceMapRunner.run(HceMapRunner.java:88)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:383)
	at org.apache.hadoop.mapred.Child.main(Child.java:226)
Caused by: java.lang.Throwable: TaskContext closeAll() failed!
	at org.apache.hadoop.mapred.hce.BinaryProtocol$UplinkReaderThread.run(BinaryProtocol.java:143)

Someone know what's going on?   Thanks so much.

**Comment by Tarrasch** [comment]
Closing. At least mention luigi in your bug reports. Luigi just launches hadoop subprocesses, try debugging that instead. :)
