### ISSUE TITLE
TypeError: 'set' object has no attribute '__getitem__' on creating task with cls.from_str_params()

### ISSUE THREAD

**Issue by samuell** [spotify/luigi#1158]
Hi,

I have this example code:

```python
import luigi

class ATask(luigi.Task):
    avalue = luigi.IntParameter()
    def output(self):
        return 'afile.txt'
    def run(self):
        with self.output().open('w') as outf:
            outf.write(str(self.avalue))

if __name__ == '__main__':
    t = ATask.from_str_params({'avalue', '0'})
```

... which generates the following output:

```bash
$ python error.py 
Traceback (most recent call last):
  File "error.py", line 12, in <module>
    t = ATask.from_str_params({'avalue', '0'})
  File "/home/samuel/.pyenv/versions/2.7.8/lib/python2.7/site-packages/luigi/task.py", line 297, in from_str_params
    value = param.parse_from_input(param_name, params_str[param_name])
TypeError: 'set' object has no attribute '__getitem__'
```

I have no clue why params_str is a set, in [this line](https://github.com/spotify/luigi/blob/master/luigi/task.py#L307).

Luigi version: 1.3.0

**Comment by samuell** [comment]
Never mind.

**Comment by erikbern** [comment]
what was the issue?

**Comment by samuell** [comment]
I sent in a wrongly formatted python dict :blush:

**Comment by samuell** [comment]
`{'avalue', '0'}` instead of `{'avalue': '0'}`

**Comment by samuell** [comment]
But there is another issue here, that it would be good if <class>.from_str_params() would warn for non-string keys or values, since otherwise very strange and errors might occur, but I'll open a separate issue for that.
