### ISSUE TITLE
[Spark Configuration] Can't pass Spark property using the conf when the option contains an equals

### ISSUE THREAD

**Issue by MezianeMehdi** [spotify/luigi#1539]
In spark configuration, the **conf** can't have some options with an equals inside:

[spark]
conf: spark.executor.extraJavaOptions=-Darchaius.deployment.environment=dev

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 162, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 113, in _run_get_new_deps
    task_gen = self.task.run()
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/spark.py", line 235, in run
    args = list(map(str, self.spark_command() + self.app_command()))
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/spark.py", line 214, in spark_command
    command += self._dict_arg('--conf', self.conf)
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/spark.py", line 138, in conf
    return self._dict_config(configuration.get_config().get("spark", "conf", None))
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/spark.py", line 261, in _dict_config
    return dict(map(lambda i: i.split('='), config.split('|')))
ValueError: dictionary update sequence element #0 has length 3; 2 is required

As a fix, it could be split only on the first equals : 

luigi/contrib/spark.py
```
  def _dict_config(self, config):
        if config and isinstance(config, six.string_types):
            return dict(map(lambda i: i.split('=',1), config.split('|')))
```

**Comment by erikbern** [comment]
great if you want to submit a PR!
