### ISSUE TITLE
Execution summary crashes on a date parameter being None

### ISSUE THREAD

**Issue by deuxpi** [spotify/luigi#1573]
There seem to be some issues with the execution summary that I'm just starting to investigate. We're  always lagging master by a few days and this crash happened in an installation from commit dd37d973cfef2a1f93aad816c17a6e834705eb46.

This is the end of the log from a run of `luigi --local-scheduler --module tasks DailyFlow` of a wrapper task that takes a DateParameter, but uses its default parameter value which is yesterday's date. The task is pretty much:

```python
class DailyFlow(luigi.WrapperTask):
    date = luigi.DateParameter(default=datetime.datetime.utcfromtimestamp(time.time()).date() - datetime.timedelta(days=1))

    def requires(self):
        yield BuildAllDimensions()
        yield BuildAggregations(date=self.date)
```

Under the `BuildAllDimensions` task, there is at least one sub-task that has a DateParameter member that is set to `None` (which in our case makes sense and means to use the latest available data).

```
2016-02-28 23:04:05,815 DEBUG [luigi-interface] Asking scheduler for work...
2016-02-28 23:04:05,816 DEBUG [luigi-interface] Done
2016-02-28 23:04:05,816 DEBUG [luigi-interface] There are no more tasks to run at this time
2016-02-28 23:04:05,832 INFO  [luigi-interface] Worker Worker(salt=531340983, workers=1, host=***, username=azkaban, pid=31882, sudo_user=ubuntu) was stopped. Shutting down Keep-Alive thread
2016-02-28 23:04:05,839 ERROR [luigi-interface] Uncaught exception in luigi
Traceback (most recent call last):
  File "/srv/azkaban/azkaban-executor-2.5.0/executions/859/local/lib/python2.7/site-packages/luigi/retcodes.py", line 61, in run_with_retcodes
    worker = luigi.interface._run(argv)['worker']
  File "/srv/azkaban/azkaban-executor-2.5.0/executions/859/local/lib/python2.7/site-packages/luigi/interface.py", line 238, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/srv/azkaban/azkaban-executor-2.5.0/executions/859/local/lib/python2.7/site-packages/luigi/interface.py", line 198, in _schedule_and_run
    logger.info(execution_summary.summary(worker))
  File "/srv/azkaban/azkaban-executor-2.5.0/executions/859/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 388, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "/srv/azkaban/azkaban-executor-2.5.0/executions/859/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 337, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "/srv/azkaban/azkaban-executor-2.5.0/executions/859/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 139, in _get_str
    first, last = _ranging_attributes(attributes, param_class)
  File "/srv/azkaban/azkaban-executor-2.5.0/executions/859/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 190, in _ranging_attributes
    next_attributes = {param_class.next_in_enumeration(attribute) for attribute in attributes}
  File "/srv/azkaban/azkaban-executor-2.5.0/executions/859/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 190, in 
    next_attributes = {param_class.next_in_enumeration(attribute) for attribute in attributes}
  File "/srv/azkaban/azkaban-executor-2.5.0/executions/859/local/lib/python2.7/site-packages/luigi/parameter.py", line 316, in next_in_enumeration
    return value + datetime.timedelta(days=self.interval)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
```

I'm not too familiar with the execution summary code so perhaps someone can beat me to submit a PR earlier for a fix.

**Comment by deuxpi** [comment]
I would be tempted to wrap the whole `_ranging_attributes` logic into a `try: except TypeError:` block and return `None, None` on errors, meaning the values don't have an obvious ordering.

**Comment by deuxpi** [comment]
> Yea. You are not really meant to have a non Date-value as the default value of a DateParameter.

I will close this issue and fix this on our side.
