### ISSUE TITLE
Running the per_task_retry_policy example fails

### ISSUE THREAD

**Issue by mxmrlv** [spotify/luigi#1865]
When i run the per_task_retry_policy example, the tasks are being retried indefinitely (or as configured in the luigi.cfg file). Effectively there is no per-task retry policy which affects the execution.

**Comment by Tarrasch** [comment]
@mxmrlv, Can you double-check that (1) Your client runs the latest code and (2) so does your server?

**Comment by chansonZ** [comment]
yes, i have the same problem and i  get the lastest code in github at now

**Comment by chansonZ** [comment]
see as fllows:
INFO: [pid 100105] Worker Worker(salt=971459027, workers=1, host=xxx.com, username=root, pid=100105) running   DynamicErrorTask1()
ERROR: [pid 100105] Worker Worker(salt=971459027, workers=1, host=xxx.com, username=root, pid=100105) failed    DynamicErrorTask1()
Traceback (most recent call last):
  File "/opt/luigi/venv/lib/python2.7/site-packages/luigi-2.6.0-py2.7.egg/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/opt/luigi/venv/lib/python2.7/site-packages/luigi-2.6.0-py2.7.egg/luigi/worker.py", line 129, in _run_get_new_deps
    task_gen = self.task.run()
  File "/opt/luigi/luigi-master/examples/per_task_retry_policy.py", line 132, in run
    raise Exception('Test Exception. Retry Index %s for %s' % (self.retry, self.task_family))
Exception: Test Exception. Retry Index 50 for DynamicErrorTask1
DEBUG: 1 running tasks, waiting for next task to finish
DEBUG: DynamicErrorTask1__99914b932b task num failures is 50 and limit is 999999999
INFO: Informed scheduler that task   DynamicErrorTask1__99914b932b   has status   FAILED
DEBUG: Asking scheduler for work...
INFO: Starting pruning of task graph
INFO: Done pruning task graph
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 5 pending tasks possibly being run by other workers
DEBUG: There are 5 pending tasks unique to this worker
DEBUG: There are 5 pending tasks last scheduled by this worker
DEBUG: Sleeping for 4.809444 seconds
