### ISSUE TITLE
Segfault in luigi

### ISSUE THREAD

**Issue by alexshires** [spotify/luigi#1935]
Hi,

When my program raises an exception, the latest version of luigi crashes with the following output:
```
ERROR: Uncaught exception in luigi
Traceback (most recent call last):
  File ".../local/lib/python2.7/site-packages/luigi/retcodes.py", line 74, in run_with_retcodes
    worker = luigi.interface._run(argv)['worker']
  File ".../local/lib/python2.7/site-packages/luigi/interface.py", line 237, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File ".../local/lib/python2.7/site-packages/luigi/interface.py", line 196, in _schedule_and_run
    success &= worker.run()
  File ".../local/lib/python2.7/site-packages/luigi/worker.py", line 1025, in run
    self._handle_next_task()
  File ".../local/lib/python2.7/site-packages/luigi/worker.py", line 908, in _handle_next_task
    self._email_task_failure(task, expl)
  File ".../local/lib/python2.7/site-packages/luigi/worker.py", line 540, in _email_task_failure
    headline="A task failed when running. Most likely run() raised an exception.",
  File ".../local/lib/python2.7/site-packages/luigi/worker.py", line 546, in _email_error
    message = notifications.format_task_error(headline, task, command, formatted_traceback)
  File ".../local/lib/python2.7/site-packages/luigi/notifications.py", line 387, in format_task_error
    formatted_exception = wrap_traceback(formatted_exception)
  File ".../local/lib/python2.7/site-packages/luigi/notifications.py", line 167, in wrap_traceback
    if email().format == 'html':
  File ".../local/lib/python2.7/site-packages/luigi/task_register.py", line 91, in __call__
    param_values = cls.get_param_values(params, args, kwargs)
  File ".../local/lib/python2.7/site-packages/luigi/task.py", line 304, in get_param_values
    if not param_obj.has_task_value(task_name, param_name):
  File ".../local/lib/python2.7/site-packages/luigi/parameter.py", line 209, in has_task_value
    return self._get_value(task_name, param_name) != _no_value
  File ".../local/lib/python2.7/site-packages/luigi/parameter.py", line 180, in _get_value
    for value, warn in self._value_iterator(task_name, param_name):
  File ".../local/lib/python2.7/site-packages/luigi/parameter.py", line 203, in _value_iterator
    yield (self._get_value_from_config(self._config_path['section'], self._config_path['name']),
  File ".../local/lib/python2.7/site-packages/luigi/parameter.py", line 177, in _get_value_from_config
    return self.parse(value)
  File ".../local/lib/python2.7/site-packages/luigi/parameter.py", line 1115, in parse
    s=s, choices=self._choices))
ValueError: 'plain' is not a valid choice from set(['plain', 'none', 'html'])
```

Any thoughts?

Regards,

Alex

**Comment by Tarrasch** [comment]
> `ValueError: 'plain' is not a valid choice from set(['plain', 'none', 'html'])`

Really looks like an issue like `"plain" != u"plain"`. Something about encodings or utf8 or bytestrings or the like. Feel free to dig this down and send a fix. :)
