### ISSUE TITLE
Sendgrid email notifications broken by new Sendgrid API

### ISSUE THREAD

**Issue by bjlange** [spotify/luigi#1956]
The v3+ version of the `sendgrid-python` package gets rid of SendGridClient in favor of SendGridAPIClient and changes a number of things, so `send_email_sendgrid` (https://github.com/spotify/luigi/blob/master/luigi/notifications.py#L236) now throws an error:
```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/retcodes.py", line 74, in run_with_retcodes
    worker = luigi.interface._run(argv)['worker']
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/interface.py", line 237, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/interface.py", line 196, in _schedule_and_run
    success &= worker.run()
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/worker.py", line 1025, in run
    self._handle_next_task()
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/worker.py", line 908, in _handle_next_task
    self._email_task_failure(task, expl)
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/worker.py", line 540, in _email_task_failure
    headline="A task failed when running. Most likely run() raised an exception.",
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/worker.py", line 547, in _email_error
    notifications.send_error_email(formatted_subject, message, task.owner_email)
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/notifications.py", line 356, in send_error_email
    recipients=recipients
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/notifications.py", line 328, in send_email
    email_sender(sender, subject, message, recipients, image_png)
  File "/home/ubuntu/.virtualenvs/janrain/local/lib/python2.7/site-packages/luigi/notifications.py", line 241, in send_email_sendgrid
    client = sendgrid_lib.SendGridClient(
AttributeError: 'module' object has no attribute 'SendGridClient'
```
It looks like the username/password auth has been gotten rid of in favor of an API key, so changes would have to be made to the configuration as well. I could open a PR for this but can't work on it right away, have some other Luigi wrangling to do first :)

**Comment by dlstadther** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [x] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [ ] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
