### ISSUE TITLE
Uncaught exception when task is finished.

### ISSUE THREAD

**Issue by andmib** [spotify/luigi#1964]
When I run any task in my file, I get the following error when the task completes succesfully:

```
ERROR: Uncaught exception in luigi
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/luigi/retcodes.py", line 74, in run_with_retcodes
    worker = luigi.interface._run(argv)['worker']
  File "/usr/local/lib/python2.7/dist-packages/luigi/interface.py", line 238, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/usr/local/lib/python2.7/dist-packages/luigi/interface.py", line 198, in _schedule_and_run
    logger.info(execution_summary.summary(worker))
  File "/usr/local/lib/python2.7/dist-packages/luigi/execution_summary.py", line 418, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "/usr/local/lib/python2.7/dist-packages/luigi/execution_summary.py", line 356, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "/usr/local/lib/python2.7/dist-packages/luigi/execution_summary.py", line 147, in _get_str
    params = _get_set_of_params(tasks)
  File "/usr/local/lib/python2.7/dist-packages/luigi/execution_summary.py", line 190, in _get_set_of_params
    params[param] = {getattr(task, param[0]) for task in tasks}
  File "/usr/local/lib/python2.7/dist-packages/luigi/execution_summary.py", line 190, in <setcomp>
    params[param] = {getattr(task, param[0]) for task in tasks}
TypeError: unhashable type: 'list'

```

Any suggestions as to what this might be?

**Comment by themalkolm** [comment]
Something is a list but it shouldn't be.

**Comment by PeteW** [comment]
Seems like a luigi parameter in one of your tasks is of type list. Luigi is attempting to write a summary of the task and stumbling whilst trying to hash this parameter. You MIGHT be able to work around this issue and keep your list parameter by declaring the parameter as insignificant with [significant=False]. Making a parameter insignificant ignores it when testing task equality and excludes it from certain reporting output. If that doesnt work you may be forced to refactor that list as some kind of alternative structure that is hashable (maybe a comma-separated string?)
