### ISSUE TITLE
can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by cynipe** [spotify/luigi#1985]
We are generating Dependent tasks dynamically based on datetime instance.
However, after upgrading 2.5.0, following error has appeared and it can not be executed:

```
Traceback (most recent call last):
  File "~/workspace/sandbox/luigi/venv/local/lib/python2.7/site-packages/luigi/worker.py", line 305, in check_complete
    is_complete = task.complete()
  File "~/workspace/sandbox/luigi/venv/local/lib/python2.7/site-packages/luigi/task.py", line 744, in complete
    return all(r.complete() for r in flatten(self.requires()))
  File "hourly_task.py", line 10, in requires
    return HourlyTask(date_hour=date_hour, text=self.text)
  File "~/workspace/sandbox/luigi/venv/local/lib/python2.7/site-packages/luigi/task_register.py", line 88, in __call__
    param_values = cls.get_param_values(params, args, kwargs)
  File "~/workspace/sandbox/luigi/venv/local/lib/python2.7/site-packages/luigi/task.py", line 354, in get_param_values
    result[param_name] = params_dict[param_name].normalize(arg)
  File "~/workspace/sandbox/luigi/venv/local/lib/python2.7/site-packages/luigi/parameter.py", line 490, in normalize
    delta = (dt - self.start).total_seconds()
TypeError: can't subtract offset-naive and offset-aware datetimes
```

Reproducible code is as follows:
```python
import luigi
import dateutil.parser


class Invoke(luigi.WrapperTask):
    text = luigi.Parameter()

    def requires(self):
        date_hour = dateutil.parser.parse('2017-01-01T10:00+09:00') # offset-aware instance causes this error
        return HourlyTask(date_hour=date_hour, text=self.text)


class HourlyTask(luigi.Task):
    date_hour = luigi.DateHourParameter()
    text = luigi.Parameter()

    def run(self):
        with self.output().open('w') as output:
                print self.text
                output.write(self.text)

    def output(self):
        return luigi.LocalTarget(path='/tmp/hourly_task_{}.txt'.format(self.date.strftime('%Y%m%d')))


if __name__ == '__main__':
    luigi.run()
```

Actually, it seems like https://github.com/spotify/luigi/commit/f9562627a8142560b170c6f9d01f8237cac8fa63 causes this error.

**Comment by erikbern** [comment]
Nice catch. Would love it if you can put together a fix for it, ideally with a unit test!

**Comment by cynipe** [comment]
@erikbern 

changing _UNIX_EPOCH[[1]] to following code does work.
```
_UNIX_EPOCH = datetime.datetime.utcfromtimestamp(0).replace(tzinfo=pytz.utc)
```

However, in that way, users need to define all of the datatime instance as offset-aware, so it is not good enough. Possible solution is...

- fallback to UTC(or local timezone) if the datetime instance is offset-naive
- provide new config for timezone, default UTC
- or else...

what do you think? any ideas?

[1]: https://github.com/spotify/luigi/blob/f9562627a8142560b170c6f9d01f8237cac8fa63/luigi/parameter.py#L270

**Comment by Tarrasch** [comment]
@cynipe, thanks for this issue! What version did you upgrade from? :)

I'm not sure if it's a good thing or bad thing that it started to crash. I think we shouldn't add any "fix" to luigi here. I rather have users stumble upon this problem and be forced to think how they want an offset-aware datetime to be converted to an offset-naive datetime. Having a "default" behavior in luigi sounds dangerous.

**Comment by cynipe** [comment]
@Tarrasch we use 2.0.1, so it's bit old one. Actually https://github.com/spotify/luigi/commit/f9562627a8142560b170c6f9d01f8237cac8fa63 is released in 2.1.0, so to me, it is wonder that no issues filed. no one faced this issue before? no offense, just wondering :)

> I think we shouldn't add any "fix" to luigi here. 

Is your "any" includes fixing `_UNIX_EPOCH` to offset-aware instance?
IMHO, It seems more uncomfortable to "remove" the offset information.

**Comment by Tarrasch** [comment]
My reasoning is something along the lines that it's not clear what the hour of `2017-01-01T10:00+09:00` is, nor if it's equal to `2017-01-01T11:00+08:00` or not. Hence in scheduling applications I think I would most often want a time-value without timezone awareness. Most users probably do something like described in the docs [here](http://luigi.readthedocs.io/en/stable/api/luigi.parameter.html#luigi.parameter.DateParameter).

On the other hand, it should be just a `datetime` value without any magic around it. Do you know why luigi can't just accept both offset-aware and offset-naive datetimes? I mean currently it crashes on offset-aware, and with your `_UNIX_EPOCH` fix it will crash on offset-naive you say?
