### ISSUE TITLE
GCSClient.remove() fails with "Request Entity Too Large"

### ISSUE THREAD

**Issue by ulzha** [spotify/luigi#2059]
We have had GCSClient.move() fail to remove large directories. This error occurs in `self.remove(source_path)` after performing `self.copy(source_path, destination_path)` successfully.

```
Traceback (most recent call last):
...
    fs.move(temp_file, destination)
  File "/src/luigi/luigi/contrib/gcs.py", line 318, in move
    self.remove(source_path)
  File "/src/luigi/luigi/contrib/gcs.py", line 239, in remove
    req.execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 1411, in execute
    self._execute(http, self._order, self._requests)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 1346, in _execute
    raise HttpError(resp, content, uri=self._batch_uri)
HttpError: <HttpError 413 when requesting https://www.googleapis.com/batch returned "Request Entity Too Large">
```

The reason seems to be that the lines before req.execute() build up too big a batch request.

**Comment by lesn-v** [comment]
Hi, 
do you plan fixing it any time soon?

**Comment by dlstadther** [comment]
@lesn-v Feel free to take a stab at fixing this is you'd like! All contributions are welcome!

**Comment by lesn-v** [comment]
Just added a workaround param to be able to limit the number of files to be deleted per operation. I know it's not the best solution, please let me know if you think something better can be done here.

Thank you!

PS. I'm not good at contributing to opensource projects..
