### ISSUE TITLE
Luigi master is falling down due to JSON serialisation errors in task state output.

### ISSUE THREAD

**Issue by mrjj** [spotify/luigi#2174]
When task error output containing non JSON-serializable symbols Luigi master is failing.

We are getting following error:

finished run
number of examples per pass = 133
passes used = 4
weighted example sum = 532.000000
weighted label sum = -4.000000
average loss = 0.678752 h
best constant = -0.015038
best constant's loss = 0.693119
total feature number = 368952
WARNING: model file has set of {-q, --cubic, --interactions} settings stored, but they'll be OVERRIDEN by set of {-q, --cubic, --interactions} settings from command line.
XXX:/var/log$ cat ./XXX/run.log.1 | grep -C 10 json\.dump
Traceback (most recent call last):
  File "/var/lib/XXX", line 277, in <module>
    success = luigi.build([MainTask(dt)], workers=10, scheduler_port=int(config.LUIGID_PORT))
  File "/usr/share/XXX/local/lib/python2.7/site-packages/luigi/interface.py", line 263, in build
    return _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)['success']
  File "/usr/share/XXX/local/lib/python2.7/site-packages/luigi/interface.py", line 196, in _schedule_and_run
    success &= worker.run()
  File "/usr/share/XXX/local/lib/python2.7/site-packages/luigi/worker.py", line 1054, in run
    self._handle_next_task()
  File "/usr/share/XXX/local/lib/python2.7/site-packages/luigi/worker.py", line 950, in _handle_next_task
    expl=json.dumps(expl),
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    return encode_basestring_ascii(o)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb4 in position 7091: invalid start byte
--- SOME OUTPUT CONTAINING "BAD" SYMBOLS ---

I propose to make controlled exception catch around JSON serialisation with fallback to the latin1 encoding that is completely free from this kind of error.

**Comment by Tarrasch** [comment]
Can you please:

 * fix the formatting of your issue (otherwise we'll have to close it per recent [policy](https://raw.githubusercontent.com/spotify/luigi/master/ISSUE_TEMPLATE.md))
 * add a runnable small example reproducing this?

Also remove any unnecessary information to this issue please.
