### ISSUE TITLE
AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

### ISSUE THREAD

**Issue by murali6688** [spotify/luigi#2198]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/luigi/worker.py", line 172, in run
    missing = [dep.task_id for dep in self.task.deps() if not dep.complete()]
  File "/usr/local/lib/python2.7/site-packages/luigi/task.py", line 547, in complete
    return all(map(lambda output: output.exists(), outputs))
  File "/usr/local/lib/python2.7/site-packages/luigi/task.py", line 547, in <lambda>
    return all(map(lambda output: output.exists(), outputs))
  File "/usr/local/lib/python2.7/site-packages/luigi/target.py", line 243, in exists
    return self.fs.exists(path)
  File "/home/dev-user/scripts/python/Example/gcs.py", line 197, in exists
    if self._obj_exists(bucket, obj):
  File "/home/dev-user/scripts/python/Example/gcs.py", line 139, in _obj_exists
    self.client.objects().get(bucket=bucket, object=obj).execute()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/http.py", line 827, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/http.py", line 154, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 616, in new_request
    self._refresh(request_orig)
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 873, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 900, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 1611, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/service_account.py", line 396, in _generate_assertion
    key_id=self._private_key_id)
  File "/usr/local/lib/python2.7/site-packages/oauth2client/crypt.py", line 97, in make_signed_jwt
    signature = signer.sign(signing_input)
  File "/usr/local/lib/python2.7/site-packages/oauth2client/_pycrypto_crypt.py", line 101, in sign
    return PKCS1_v1_5.new(self._key).sign(SHA256.new(message))
  File "/usr/lib64/python2.7/dist-packages/Crypto/Signature/PKCS1_v1_5.py", line 112, in sign
    m = self._key.decrypt(em)
  File "/usr/lib64/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 174, in decrypt
    return pubkey.pubkey.decrypt(self, ciphertext)
  File "/usr/lib64/python2.7/dist-packages/Crypto/PublicKey/pubkey.py", line 93, in decrypt
    plaintext=self._decrypt(ciphertext)
  File "/usr/lib64/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 235, in _decrypt
    r = getRandomRange(1, self.key.n-1, randfunc=self._randfunc)
  File "/usr/lib64/python2.7/dist-packages/Crypto/Util/number.py", line 123, in getRandomRange
    value = getRandomInteger(bits, randfunc)
  File "/usr/lib64/python2.7/dist-packages/Crypto/Util/number.py", line 104, in getRandomInteger
    S = randfunc(N>>3)
  File "/usr/lib64/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/lib64/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/lib64/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 137, in read
    self._check_pid()
  File "/usr/lib64/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 153, in _check_pid
    raise AssertionError("PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()")
AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

**Comment by murali6688** [comment]
Scripts works perfectly fine on windows but fails on linux
