### ISSUE TITLE
how to write protobuf message with luigi?

### ISSUE THREAD

**Issue by tyrant0604** [spotify/luigi#2214]
reducer is like:
reducer(self, key, values):
    ......
    ins = instance_pb2.Instance()
    serialized_ins = ins.SerializeToString()
    yield [ serialized_ins ]

Traceback (most recent call last):
  File "mrrunner.py", line 97, in <module>
    main()
  File "mrrunner.py", line 90, in main
    Runner().run(kind, stdin=stdin, stdout=stdout)
  File "mrrunner.py", line 55, in run
    self.job.run_reducer(stdin, stdout)
  File "luigi/contrib/hadoop.py", line 1006, in run_reducer
    self.writer(outputs, stdout)
  File "luigi/contrib/hadoop.py", line 835, in writer
    print("\t".join(output), file=stdout)
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "prepare_running_instance.py", line 448, in reducer
    yield [serialized_ins]
GeneratorExit

**Comment by Tarrasch** [comment]
Closing as of this is a poorly formatted issue. Please see the issue-template.
