### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str' with SGEJobTask

### ISSUE THREAD

**Issue by sdhutchins** [spotify/luigi#2215]
I'm trying to run the following code as a test.

```python
import logging
import os
import luigi
from luigi.contrib.sge import SGEJobTask

logger = logging.getLogger('luigi-interface')


class TestJobTask(SGEJobTask):

    SGEJobTask.parallel_env = 'pbs'
    SGEJobTask.shared_tmp_dir = '/work5/r2295/tmp'
    SGEJobTask.job_name = 'sdhtest'

    i = luigi.Parameter()

    def work(self):
        logger.info('Running test job...')
        with open(self.output().path, 'wb') as outfile:
            outfile.write(b'This is a test!!!')

    def output(self):
        return luigi.LocalTarget(os.path.join('/work5/r2295/tests/sge_tests',
                                              'testfile_' + str(self.i)))


if __name__ == '__main__':
    tasks = [TestJobTask(i=str(i), n_cpu=i+1) for i in range(3)]
    luigi.build(tasks, local_scheduler=True, workers=3)
```

I continue to get the following error:

```
DEBUG: Checking if TestJobTask(i=0) is complete
INFO: Informed scheduler that task   TestJobTask_0_d010c9c495   has status   PENDING
DEBUG: Checking if TestJobTask(i=1) is complete
INFO: Informed scheduler that task   TestJobTask_1_64a8d99e05   has status   PENDING
DEBUG: Checking if TestJobTask(i=2) is complete
INFO: Informed scheduler that task   TestJobTask_2_a9facda7c5   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 3 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 3
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
INFO: [pid 9313] Worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310) running   TestJobTask(i=0)
INFO: Tmp dir: /work5/r2295/tmp/TestJobTask_0_d010c9c495-3c3a12a51392d284
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 9314] Worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310) running   TestJobTask(i=1)
ERROR: [pid 9313] Worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310) failed    TestJobTask(i=0)
Traceback (most recent call last):
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/worker.py", line 129, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/contrib/sge.py", line 259, in run
    self._init_local()
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/contrib/sge.py", line 245, in _init_local
    self._dump(self.tmp_dir)
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/contrib/sge.py", line 280, in _dump
    d = d.replace('(c__main__', "(c" + module_name)
TypeError: a bytes-like object is required, not 'str'
INFO: Tmp dir: /work5/r2295/tmp/TestJobTask_1_64a8d99e05-d47a5cebd7f622a3
DEBUG: 3 running tasks, waiting for next task to finish
INFO: [pid 9315] Worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310) running   TestJobTask(i=2)
ERROR: [pid 9314] Worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310) failed    TestJobTask(i=1)
Traceback (most recent call last):
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/worker.py", line 129, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/contrib/sge.py", line 259, in run
    self._init_local()
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/contrib/sge.py", line 245, in _init_local
    self._dump(self.tmp_dir)
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/contrib/sge.py", line 280, in _dump
    d = d.replace('(c__main__', "(c" + module_name)
TypeError: a bytes-like object is required, not 'str'
INFO: Tmp dir: /work5/r2295/tmp/TestJobTask_2_a9facda7c5-354c141d2118e7c4
ERROR: [pid 9315] Worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310) failed    TestJobTask(i=2)
Traceback (most recent call last):
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/worker.py", line 129, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/contrib/sge.py", line 259, in run
    self._init_local()
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/contrib/sge.py", line 245, in _init_local
    self._dump(self.tmp_dir)
  File "/home/ums/r2295/.local/lib/python3.5/site-packages/luigi/contrib/sge.py", line 280, in _dump
    d = d.replace('(c__main__', "(c" + module_name)
TypeError: a bytes-like object is required, not 'str'
INFO: Informed scheduler that task   TestJobTask_0_d010c9c495   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: TestJobTask_2_a9facda7c5 is currently run by worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310)
DEBUG: TestJobTask_1_64a8d99e05 is currently run by worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310)
INFO: Informed scheduler that task   TestJobTask_1_64a8d99e05   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: TestJobTask_2_a9facda7c5 is currently run by worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310)
INFO: Informed scheduler that task   TestJobTask_2_a9facda7c5   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 3 pending tasks possibly being run by other workers
DEBUG: There are 3 pending tasks unique to this worker
DEBUG: There are 3 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=162029851, workers=3, host=sequoia, username=r2295, pid=9310) was stopped. Shutting down Keep-Alive thread
INFO:
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 3 failed:
    - 3 TestJobTask(...)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

```

Any suggestions about what is causing this TypeError `TypeError: a bytes-like object is required, not 'str'`?

@jfeala

**Comment by seasick-pete** [comment]
Hi,

Does changing the following help?

```outfile.write(b'This is a test!!!')```
to 
```outfile.write('This is a test!!!')```

**Comment by sdhutchins** [comment]
@seasick-pete I need to back through this and test the original. I ended up using @jfeala's SGEJobTask to build my own SGEJobTask that's more applicable to the SGI machine I use. Not many edits, but enough.

When I revisit this, I'll have a better idea of what is/was breaking, but it had to do with pickling (I think). I had to change everything to bytes.

**Comment by njanetos** [comment]
Any insights on what is causing this? I get the same error with the example code provided in the [module documentation](http://luigi.readthedocs.io/en/stable/api/luigi.contrib.sge.html).

**Comment by mivade** [comment]
This is caused by mixing `bytes` and `str` in the `_dump` method.
