### ISSUE TITLE
Windows Error: Cannot open output with format parameter specified

### ISSUE THREAD

**Issue by shaynewang** [spotify/luigi#2218]
My output definition is:
```
    def output(self):
        fn = os.path.join(self.output_dir,
                          'output_files','export.tsv')
        return luigi.LocalTarget(fn, format=luigi.format.Gzip)
```
But when I try to open the output file to write I get the error below:
```
Traceback (most recent call last):
  File "C:\Users\levinjos\AppData\Local\Continuum\Anaconda2\lib\site-packages\luigi\worker.py", line 192, in run
    new_deps = self._run_get_new_deps()
  File "C:\Users\levinjos\AppData\Local\Continuum\Anaconda2\lib\site-packages\luigi\worker.py", line 144, in _run_get_ne
w_deps
    requires = task_gen.send(next_send)
  File "c:\users\levinjos\classifications_pipeline\classifications\retrieval.py", line 256, in run
    with self.output().open('w') as fl:
  File "C:\Users\levinjos\AppData\Local\Continuum\Anaconda2\lib\site-packages\luigi\file.py", line 134, in open
    return self.format.pipe_writer(atomic_file(self.path))
  File "C:\Users\levinjos\AppData\Local\Continuum\Anaconda2\lib\site-packages\luigi\format.py", line 492, in pipe_writer

    return OutputPipeProcessWrapper(args, output_pipe)
  File "C:\Users\levinjos\AppData\Local\Continuum\Anaconda2\lib\site-packages\luigi\format.py", line 183, in __init__
    close_fds=True)
  File "C:\Users\levinjos\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 667, in __init__
    raise ValueError("close_fds is not supported on Windows "
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```
Line here is the cause to the problem, do we need to close file descriptors if the platform is mswindows?:
https://github.com/spotify/luigi/blob/bb9c8f94314c91306475cb568a62d106788a106e/luigi/format.py#L103-L107

luigi (2.6.2)
Machine: Windows 7
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)] on win32

**Comment by atharvai** [comment]
I've had this issue on Windows 10 64 bit, Python2.7.14 (64bit), luigi>=2.3.0.
Is there guidance on a workaround until this is fixed?

**Comment by omkarprabhu-98** [comment]
I've had the same issue on Windows 10 64 bit, Python 3.6.5 (64bit), luigi 2.7.5

**Comment by charlesoblack** [comment]
This error is still occurring:

    Traceback (most recent call last):
      File "c:\python37\lib\site-packages\luigi\worker.py", line 199, in run
        new_deps = self._run_get_new_deps()
      File "c:\python37\lib\site-packages\luigi\worker.py", line 139, in _run_get_new_deps
        task_gen = self.task.run()
      File "Q:\Pipelines\pipeline.py", line 244, in run
        with self.input()[1].open('r') as f:
      File "c:\python37\lib\site-packages\luigi\local_target.py", line 166, in open
        return self.format.pipe_reader(fileobj)
      File "c:\python37\lib\site-packages\luigi\format.py", line 501, in pipe_reader
        return InputPipeProcessWrapper(['bzcat'], input_pipe)
      File "c:\python37\lib\site-packages\luigi\format.py", line 88, in __init__
        self._process = command if isinstance(command, subprocess.Popen) else self.create_subprocess(command)
      File "c:\python37\lib\site-packages\luigi\format.py", line 107, in create_subprocess
        close_fds=True)
      File "c:\python37\lib\subprocess.py", line 662, in __init__
        raise ValueError("preexec_fn is not supported on Windows "
    ValueError: preexec_fn is not supported on Windows platforms

code:


    def run(self):
	    import pickle

	    self.output().makedirs()

	    with self.input()[1].open('r') as f:
	    	data = pickle.load(f)

**Comment by Tarrasch** [comment]
I really can't help out here, sorry! But I can review PRs!

**Comment by tjrileywisc** [comment]
@charlesoblack maybe a simple change to `create_subprocess` in  InputPipeProcessWrapper will help? Check the PR I just submitted- creating the subprocess without the `preexec_fn` and `close_fds` arguments worked for my task.
