### ISSUE TITLE
is it possible to use logging when workers>1?

### ISSUE THREAD

**Issue by simonm3** [spotify/luigi#2247]
Any logging messages in the "run" method of a task are lost when workers>1. Is there a way to get logging to work across multiple workers?

Example logs to file and screen as per my logging config with workers=1. However with workers=4 the "run" messages are lost.

> import logging as log
> #logging.basicConfig(level=logging.INFO)
> import logcon
> from luigi.interface import build, setup_interface_logging
> from test import Task
> setup_interface_logging.has_run = True
> logging.getLogger("luigi-interface").setLevel(logging.WARNING)
> build([Task()], workers=1)

test.py contains

> import logging as log
> import luigi
> 
> class Task(luigi.Task):
>     def __init__(self):
>         super().__init__()
>         log.info("starting")
> 
>     def complete(self):
>         log.info("checking complete")
>         return False
> 
>     def run(self):
>         log.info("running")
> 
>     def requires(self):
>         return []

**Comment by simonm3** [comment]
I have a workaround for this which is OK but still requires a function call at the start of every run function. Would be better if included in luigi.

```
import logging
import luigi
from luigi.interface import build, setup_interface_logging
from multiprocessing import Queue
from logging.handlers import QueueHandler, QueueListener

q = Queue()

def run(tasks, *args, **kwargs):
    """ run tasks with queuelistener to handle logging """
    setup_interface_logging.has_run = True
    workers = kwargs.get("workers", 1) > 1
    if workers:
        log=logging.getLogger()
        listener = QueueListener(q, *log.handlers)
        listener.start()
    
    build(tasks, *args, **kwargs)
    
    if workers:
        listener.stop()

class Task(luigi.Task):
    """ redirect logging to queue """
    def __init__(self):
        """ add q to process """
        super().__init__()
        self.q = q

    def enable(self):
        """ call at start of each run process to initialise settings and redirect logging to queue """
        
        # for 1 worker leave settings alone
        log = logging.getLogger()
        if log.handlers:
            return

        # for multiple workers load settings but replace handlers with queue
        from logcon import log
        log.handlers = []
        log.addHandler(QueueHandler(self.q))

####### EXAMPLE USAGE #########################################################

class Test(Task):

    def complete(self):
        return False

    def run(self):
        self.enable()

        log = logging.getLogger()
        log.debug("running")
        log.info("running")
        log.warning("running")

        log = logging.getLogger("runlog")
        log.debug("running")
        log.info("running")
        log.warning("running")

        log = logging.getLogger("luigi-interface")
        log.debug("running")
        log.info("running")
        log.warning("running")

    def requires(self):
        return []
```

**Comment by mattmcknight** [comment]
I haven't run into this problem despite many workers and a lot of logging, does it only occur when you have two log targets?

**Comment by simonm3** [comment]
There are no log handlers defined when I start the "run" method. I have no_configure_logging=True as I want to set my own logging  settings - but really I want to only set them once! I am on windows 10. 

Works fine with 1 worker. Also my workaround work fine too - which I updated as below so it now works better if anyone else has this problem and it is not fixed.

```
""" enable multiprocess logging for luigi """

import logging
import luigi
import luigi.interface
from multiprocessing import Queue
from logging.handlers import QueueHandler, QueueListener
import types

q = Queue()

def build(tasks, *args, **kwargs):
    """ wrap luigi build to enable multiprocess logging """
    if kwargs.get("workers", 1) == 1:
        return luigi.interface.build(tasks, *args, **kwargs)
    
    # create queuelistener to process logging messages
    l = QueueListener(q, *logging.getLogger().handlers)
    l.start()
    result = luigi.interface.build(tasks, *args, **kwargs)
    l.stop()
    return result

class Task(luigi.Task):
    """ redirect logging to queue """
    def __init__(self, *args, **kwargs):
        """ add q to process """
        super().__init__(*args, **kwargs)
        self.q = q

    def multilog(self):
        """ configure multiprocess logging """

        # for 1 worker leave settings alone
        log = logging.getLogger()
        if not log.handlers:
            # for multiple workers load logging settings and replace handlers with queue
            from logcon import log
            log.handlers = []
            log.addHandler(QueueHandler(self.q))

    def multilog_wrapper(self, func):
        """ wraps run to call multilog at start """
        def wrapped(*args, **kwargs):
            self.multilog()
            return func(*args, **kwargs)
        return wrapped

    def __getattribute__(self, name):
        """ wrap run method with multi-process logging  """
        attr = super().__getattribute__(name)
        if type(attr) == types.MethodType and name=="run":
            attr = self.multilog_wrapper(attr)
        return attr
```

**Comment by mattmcknight** [comment]
Here's what I have that works with multiple handlers and multiple workers, maybe you can work backwards from this:

```
import logging
import luigi

LOGGER = logging.getLogger(__name__)
LOGGER.setLevel(logging.DEBUG)
LOGGER.addHandler(logging.StreamHandler())
LOGGER.addHandler(logging.FileHandler('output.log'))

class LoggingTask(luigi.Task):
    item = luigi.Parameter()

    def requires(self):
       LOGGER.debug("in requires")
       return

    def output(self):
        LOGGER.debug("in output")
        return luigi.LocalTarget("output" + str(self.item))

    def run(self):
        LOGGER.debug("in run")
        output = open("output" + str(self.item), "w")
        output.close()


class ParentTask(luigi.WrapperTask):

    def requires(self):
        LOGGER.debug("in parent task requires")
        child_tasks = []
        for i in range(0,4):
            child_tasks.append(LoggingTask(item=str(i)))
        return child_tasks
```

run at command line with:

`PYTHONPATH=. luigi --module logging_test ParentTask --workers 4`

**Comment by simonm3** [comment]
Thanks Matt,

That does work. However if I run the loggingtask directly rather than
parentclass then there are no logging messages which seems odd.

In my original case I am running from a jupyter notebook and wanting the
log messages to appear in the cell output using the log settings from the
jupyter notebook rather than setting them in the file.

simon

**Comment by mattmcknight** [comment]
I get the logging messages running the LoggingTask directly with four workers. (it's just that there is only one set because there is only one task). Make sure you delete the output0 file or whatever param you pass in for item.

**Comment by simonm3** [comment]
You are right. Sorry must have forgotten to reset the output. It does work
with 4 workers but only if logging settings are made in the file - which is
not always the case e.g. if you are running a notebook. Also even when
settings are made in the file then the streamhandler does not pass these
back from the run method to the notebook.

**Comment by hirolau** [comment]
I have also experienced issues with multi-worker logging and want to add that this is a Windows problems. The os.fork() process, which allows the state of the parent to be maintained in the forked process, does not exist on Windows. Instead, the multiprocessing library uses the spawn method and that causes the logging configuration to be lost.

In the example above by _mattmcknight_ multiple workers do indeed work as long as all tasks are defined in a single file, so that when the new process starts it reads the config again. If `LoggingTask` was moved to a separate file and only initialized using `import logging, logger = logging.GetLogger(__name__)` the configuration would be lost.

I have run the above setup on both Windows and Linux and they behave differently! In Linux the logging config is kept between the workers, in Windows, it is lost.

I think I will solve this by simply create a log-setup function with a cache in a module and call that at the top of every file in my code. That way anytime a worker is created it reloads the logging config.

https://stackoverflow.com/questions/1268252/possible-to-share-in-memory-data-between-2-separate-processes

https://docs.python.org/3/library/multiprocessing.html

**Comment by mattmcknight** [comment]
>  If LoggingTask was moved to a separate file and only initialized using import logging, logger = logging.GetLogger(__name__) the configuration would be lost.

If they are in different files/modules, the __name__ will resolve to a different object. It is possible to set up a parent logger structure as well, by defining the logger in a logger which is a parent to both modules, or to set up the handlers in a config file that both classes read.

**Comment by hirolau** [comment]
>by defining the logger in a logger which is a parent to both modules ...

In Linux this works fine, but my point was that this is not viable in Windows, as the parent logger setup is lost when workers are spawned (and not forked). 

> or to set up the handlers in a config file that both classes read ...

This is how you must do it in Windows, but luigi by default does not help you with this.

**Comment by hirolau** [comment]
Here is a minimal example that shows why. In this case, the `SHARED_VALUE` variable would represent the root logger. 3 files:

In parent.py:

```python
import luigi
from shared_variable import set_shared_value
from child import ChildTask

# Same functionality as setting up a logger:
set_shared_value('foo')

class ParentTask(luigi.WrapperTask):
    def requires(self):
        for i in range(0,4):
            yield ChildTask(item=str(i))
```

In child.py:

```python
import luigi
from shared_variable import get_shared_value

class ChildTask(luigi.Task):
    
    item = luigi.Parameter()

    def output(self):
        return luigi.LocalTarget("output" + str(self.item))

    def run(self):
        value = get_shared_value()
        with open("output" + str(self.item), "w") as file:
            file.write(value) 
```

In shared_variable.py

```python
SHARED_VALUE = None

def set_shared_value(value):
  global SHARED_VALUE
  SHARED_VALUE = value

def get_shared_value():
  global SHARED_VALUE
  if SHARED_VALUE is None:
    raise Exception('SHARED_VALUE has not been set, please run set_shared_value() first.')
  return SHARED_VALUE
```

Running this in linux with any number of workers works fine (`luigi --module parent ParentTask --local-scheduler --workers 4`). Same in Windows with 1 worker. The output files get created and all contain the value `foo` . But on Windows with multiple workers:

```
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\lib\site-packages\luigi\worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "C:\Users\user\Miniconda3\lib\site-packages\luigi\worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "C:\Users\user\Desktop\luigi\child.py", line 13, in run
    value = get_shared_value()
  File "C:\Users\user\Desktop\luigi\shared_variable.py", line 10, in get_shared_value
    raise Exception('SHARED_VALUE has not been set, please run set_shared_value() first.')
Exception: SHARED_VALUE has not been set, please run set_shared_value() first.
```

**Comment by stolpovsky** [comment]
I also have the same issue: no log output is generated when running with 2 or more workers. Everything works as expected with `--workers=1`. I am on Windows 10, luigi 2.7.2.

Related to this, is there a way to configure luigi to send log to separate files for each worker? In my case the number of workers is <100, and having each use a separate log file will make logs much easier to read.

**Comment by inderdeepdhir** [comment]
> I also have the same issue: no log output is sent to file when running with 2 or more workers (log gets printed to sys.stdout instead). Everything works as expected with `--workers=1`. I am on Windows 10, luigi 2.7.2.
> 
> Related to this, is there a way to configure luigi to send log to separate files for each worker? In my case the number of workers is <100, and having each use a separate log file will make logs much easier to read.

Although the issue is now closed, here is a solution that I used to configure luigi to send log to separate files for each worker - subclassed the FileHandler to suffix the PID on the filename, then used this handler in the logging config.


`import os
from logging import FileHandler

PID = ''.join(['.pid_',str(os.getpid())])
def new_filename(filename): return ''.join([filename, PID])

class PidFileHandler(FileHandler):
    # change the default filename to include the process pid
    # so that the same filename can be used with multiple processes without conflict
    def __init__(self, filename, mode='a', encoding=None, delay=False, errors=None)
        super().__init__(new_filename(filename), mode, encoding, delay, errors)
`
