### ISSUE TITLE
Failing execution_summary

### ISSUE THREAD

**Issue by vinaybabunaidu** [spotify/luigi#2261]
Hi all,
I am currently facing an issue with the execution_summary where the attributes is of below format.
`attributes = set([datetime.datetime(2017, 8, 4, 0, 0), datetime.datetime(2017, 8, 3, 0, 0)])`

Error : 
```Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/luigi/luigi_shell.py", line 315, in run
    scheduler_port=options.luigi_port)
  File "/luigi/luigi/interface.py", line 270, in build
    return _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)['success']
  File "/luigi/luigi/interface.py", line 204, in _schedule_and_run
    logger.info(execution_summary.summary(worker))
  File "/luigi/luigi/execution_summary.py", line 428, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "/luigi/luigi/execution_summary.py", line 362, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "/luigi/luigi/execution_summary.py", line 154, in _get_str
    first, last = _ranging_attributes(attributes, param_class)
  File "/luigi/luigi/execution_summary.py", line 209, in _ranging_attributes
    next_attributes = {param_class.next_in_enumeration(attribute) for attribute in attributes}
  File "/luigi/luigi/execution_summary.py", line 209, in <setcomp>
    next_attributes = {param_class.next_in_enumeration(attribute) for attribute in attributes}
AttributeError: 'str' object has no attribute 'next_in_enumeration'```

**Comment by vinaybabunaidu** [comment]
a follow up question; what should be the `param_class` value ?
