### ISSUE TITLE
InvalidParameterException in contrib.ecs _get_task_statuses

### ISSUE THREAD

**Issue by jhrf** [spotify/luigi#2365]
I am currently writing a data processing pipeline with luigi utilising the ecs module. 

Everything was working fine when using the local-scheduler. However, I have noticed that when I run the pipeline using the central scheduler with two or more workers I am seeing a bug surrounding the acquisition of a taskArn from Amazon. The problem occurs in about 50% of test runs so I think there is a concurrency issue.

I receive the following error:

> Traceback (most recent call last):
>   File "/lib/python3.6/site-packages/luigi-2.7.2-py3.6.egg/luigi/worker.py", line 194, in run
>     new_deps = self._run_get_new_deps()
>   File "/lib/python3.6/site-packages/luigi-2.7.2-py3.6.egg/luigi/worker.py", line 131, in _run_get_new_deps
>     task_gen = self.task.run()
>   File "my_pipelines/tasks/util.py", line 65, in run
>     super().run()
>   File "/lib/python3.6/site-packages/luigi-2.7.2-py3.6.egg/luigi/contrib/ecs.py", line 195, in run
>     _track_tasks(self._task_ids, self.cluster)
>   File "/lib/python3.6/site-packages/luigi-2.7.2-py3.6.egg/luigi/contrib/ecs.py", line 91, in _track_tasks
>     statuses = _get_task_statuses(task_ids, cluster)
>   File "/lib/python3.6/site-packages/luigi-2.7.2-py3.6.egg/luigi/contrib/ecs.py", line 74, in _get_task_statuses
>     response = client.describe_tasks(tasks=task_ids, cluster=cluster)
>   File "/lib/python3.6/site-packages/botocore-1.8.46-py3.6.egg/botocore/client.py", line 324, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/lib/python3.6/site-packages/botocore-1.8.46-py3.6.egg/botocore/client.py", line 622, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the DescribeTasks operation: Tasks cannot be empty.
> 

After doing a little bit of digging I think I have diagnosed the problem. It seems that the call to AWS (via a boto client) is failing either on Line 182 or 174 of ecs.py. Presumably when two requests are made almost simultaneously one of the requests is issued as a failure. The result of the failure is that the taskArn variable in the response is not initialised. Thus the tasks list is left empty and the error above is produced.

Perhaps a possible fix would be to surround the boto responses with some retry code in the event of an error. 

Thanks, 

Henry

**Comment by jhrf** [comment]
More investigation has given more insight to the problem. 

The error is caused by the `client.run_task` call on line 182. I am receiving a failure with the reason "RESOURCE:MEMORY" when there are not enough available resources for the task. The failures fails to populate the `self.task_ids` and the error above is shown.

In my case, and I suspect in other cases as well, this behaviour is not ideal. For the purposes of my pipeline I need the task to wait until resources are available and then to submit the task_run again. I have inherited the ECSTask class and overwritten the run function in order to allow the response to be wrapped like so:

` def run_task_on_ecs(self):


        # Submit the task to AWS ECS and get assigned task ID        
        overrides = self.__get_overrides__()

        valid_reasons = ['RESOURCE:MEMORY',]

        sleep_time = 20
        task_started = False
        wait = False

        while not task_started:
            response = CLIENT.run_task(taskDefinition=self.task_def_arn,
                                       overrides=overrides,
                                       cluster=self.cluster)

            if len(response['failures']) == 1:
                failure = response['failures'][0]
                if failure['reason'] in valid_reasons:
                    LOGGER.debug(
                        'ECS task status for tasks %s: %s' % \
                            (self.task_def_arn, 'WAITING'))

                    time.sleep(sleep_time)
                else:
                    raise RuntimeError(
                        'Unkown reason for ECS run_task failure ')
            elif len(response['failures']) > 1:
                raise RuntimeError(
                    ('Multiple failure reasons when trying to '
                     'run a task on the ecs cluster.'))

            else:
                self._task_ids = [task['taskArn'] for task in response['tasks']]
                self.remote_task_started = True
                task_started = True`
