### ISSUE TITLE
ERROR: Failed connecting to remote scheduler 'http://localhost:8082'

### ISSUE THREAD

**Issue by 01123899** [spotify/luigi#2459]
Hi everyone!

I need some help, I am running luigi with 6 `workers` some task long 8 hours (aprox)
It seems that the task works fine, but Luigi have some problems, and it show me this:

ERROR: Failed connecting to remote scheduler 'http://localhost:8082'
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/luigi/rpc.py", line 139, in _fetch
    response = self._fetcher.fetch(full_url, body, self._connect_timeout)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/luigi/rpc.py", line 76, in fetch
    return urlopen(full_url, body, timeout).read().decode('utf-8')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>

**Comment by DobbyH** [comment]
Do you have any more information on how this was fixed?
