### ISSUE TITLE
502 Bad Gateway error tied to 

### ISSUE THREAD

**Issue by rayrrr** [spotify/luigi#2507]
We use Luigi as an unpinned requirement that rebuilds whenever we deploy, in a cloud-hosted environment.

We deployed some changes today that did not involve our Python code; after this deploy, our service went offline with 502 Bad Gateway responses from the scheduler.

Our team dug in and found the following error:

```
AttributeError: 'Task' object has no attribute 'param_visibilities'
 File "/usr/local/lib/python3.6/site-packages/luigi/scheduler.py", line 825, in add_task
```

It looks like the Scheduler class needs to be updated to work with the latest changes to how the Task class handles param visibility included in release 2.7.7.

**Comment by Gr1f0n6x** [comment]
@rayrrr hm, it's strange =\ Probably, i missed something
I will look at this.
If it is possible, could you provide some code to reproduce it?

**Comment by rayrrr** [comment]
@Gr1f0n6x can't provide our company code, sorry, but it looks as though it'll happen with any Task run against a scheduler.

**Comment by Gr1f0n6x** [comment]
Yes, as i thought. The problem was in saving old versioned tasks.
```
    result = getattr(self._scheduler, method)(**arguments)
  File "/Users/grifon/anaconda/lib/python3.6/site-packages/luigi/scheduler.py", line 825, in add_task
    if not task.param_visibilities:
AttributeError: 'Task' object has no attribute 'param_visibilities'
```

**Comment by rayrrr** [comment]
@Gr1f0n6x we do stave state in a pickle file as per the [built-in `state_path` attribute](https://luigi.readthedocs.io/en/stable/api/luigi.scheduler.html?highlight=state_path#luigi.scheduler.scheduler.state_path) of the scheduler but that's it. We currently run our jobs as "nightly batch jobs," so there were no old tasks waiting to be executed when this happened to us AFAIK. 

The bug has something to do with https://github.com/spotify/luigi/blob/master/luigi/scheduler.py#L825 which is a conditional statement dealing with an attribute called `task.param_visibilities`, which doesn't exist in the case of the bug. It appears that this portion of the code is intending to set this attribute if it doesn't already exist...but it also seems this attribute is added on to the instance of the class at some point after it is created...so if something didn't happen as expected in that whole flow, this bug could result, because

```
>>> class Task(object):
...     builtin = 'hello'
... 
>>> task = Task()
>>> task.builtin
'hello'
>>> task.param_visibility
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Task' object has no attribute 'param_visibility'
```

so if you want to check for the existence of an attribute on a class instance:

```
>>> hasattr(task, 'param_visibility')
False
```

Might it be better to use `if hasattr(task, 'param_visibilities')` on line 825 in that conditional statement instead of `if task.param_visibilities`?

**Comment by Gr1f0n6x** [comment]
@rayrrr yes, exactly. I tried to replace this line `if not task.param_visibilities` by 
`if not getattr(task, 'param_visibilities', None)` and, at least, it solved this problem

**Comment by Gr1f0n6x** [comment]
@rayrrr i've created PR.
I believe that it will fix this issue.
