### ISSUE TITLE
S3 Remove Unable to Handle Huge Amount of Files

### ISSUE THREAD

**Issue by chunleng** [spotify/luigi#2511]
I currently have a task to schedule deletion of a certain folder in s3. When I run `self.requires().fs.remove(self.requires().path)` it runs into the following error:

```
Traceback (most recent call last):
  File "path/to/venv/.env/lib/python3.6/site-packages/luigi/worker.py", line 205, in run
    new_deps = self._run_get_new_deps()
  File "path/to/venv/.env/lib/python3.6/site-packages/luigi/worker.py", line 142, in _run_get_new_deps
    task_gen = self.task.run()
  File "path/to/tasks/script.py", line 92, in run
    target.fs.remove(target.path)
  File "path/to/venv/.env/lib/python3.6/site-packages/luigi/contrib/s3.py", line 221, in remove
    self.s3.meta.client.delete_objects(Bucket=bucket, Delete={'Objects': delete_key_list})
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/endpoint.py", line 177, in _send_request
    success_response, exception):
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/endpoint.py", line 273, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exc
eption
    raise caught_exception
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/endpoint.py", line 222, in _get_response            proxies=self.proxies, timeout=self.timeout)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in sen
d
    r = adapter.send(request, **kwargs)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 415, in sen
d
    raise ConnectionError(err, request=request)
botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

or sometimes this:

```
Traceback (most recent call last):
  File "path/to/venv/.env/lib/python3.6/site-packages/luigi/worker.py", line 205, in run
    new_deps = self._run_get_new_deps()
  File "path/to/venv/.env/lib/python3.6/site-packages/luigi/worker.py", line 142, in _run_get_new_deps
    task_gen = self.task.run()
  File "path/to/tasks/datalake/imp.py", line 93, in run
    target.fs.remove(target.path)
  File "path/to/venv/.env/lib/python3.6/site-packages/luigi/contrib/s3.py", line 221, in remove
    self.s3.meta.client.delete_objects(Bucket=bucket, Delete={'Objects': delete_key_list})
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "path/to/venv/.env/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedXML) when calling the DeleteObjects operation: The XML you provided was not well-formed or
 did not validate against our published schema
```

It seems to me that it either timeout or gets truncated when there's too many files to process.

Not sure if there is a reason behind manually `bucket.filter()` and sending to client to delete via `s3.meta.client.delete_objects()`. Personally I think that `bucket.filter().delete()` might handle in a much better way.

Both handle deletion in batch of 1000, but `bucket.filter().delete()` is a high level function that can group request into batch of 1000 keys each.

**Comment by dlstadther** [comment]
I'd be happy to review an improvement PR :) Feel free to contribute!

**Comment by dlstadther** [comment]
@chunleng I began encountering this exact thing and submitted https://github.com/spotify/luigi/pull/2529 . It'll be getting merged soon.
