### ISSUE TITLE
AWS SNS email - message too long

### ISSUE THREAD

**Issue by dfeldstarsky** [spotify/luigi#2532]
```
2018-09-24 19:17:09,789 luigi-interface[13067] INFO: Sending email to ['<aws sns arn redacted>']
2018-09-24 19:17:10,262 tornado.application[13067] ERROR: Exception in callback <bound method Scheduler.prune of <luigi.scheduler.Scheduler object at 0x7fbe240d42d0>>
Traceback (most recent call last):
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/tornado/ioloop.py", line 1026, in _run
    return self.callback()
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/scheduler.py", line 716, in prune
    self._prune_emails()
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/scheduler.py", line 743, in _prune_emails
    self._email_batcher.update()
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/batch_notifier.py", line 208, in update
    self.send_email()
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/batch_notifier.py", line 197, in send_email
    owner=owner,
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/batch_notifier.py", line 187, in _send_email
    send_email(subject, email_body, email().sender, (owner,))
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/notifications.py", line 327, in send_email
    email_sender(sender, subject, message, recipients, image_png)
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/notifications.py", line 283, in send_email_sns
    response = topic.publish(Subject=subject, Message=message)
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/dfeldman/.virtualenvs/dp/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
InvalidParameterException: An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Message too long
```

Possibly the traceback got too large? We might need to add a max len for the message and truncate? 

Not sure how to reproduce.

**Comment by dfeldstarsky** [comment]
Was able to get an email that was unreasonably large, but not enough to break the email:
```
- VideoExtractor(<param>) (1 failure)

      Traceback (most recent call last):
        File "/home/bags/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/worker.py", line 199, in run
          new_deps = self._run_get_new_deps()
        File "/home/bags/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
          task_gen = self.task.run()
        File "/home/bags/.virtualenvs/dp/local/lib/python2.7/site-packages/luigi/contrib/docker_runner.py", line 225, in run
          raise ContainerError(container, exit_status, self.command, self._image, error)
      ContainerError: Command '/video_extractor/run.sh' in image '<image>-luigi:latest' returned non-zero exit status 1: 
0it [00:00, ?it/s]
32it [00:00, 299.39it/s]
63it [00:00, 298.67it/s]
95it [00:00, 300.45it/s]
<these continue for the entire email>
```

So definitely my fault :). Possibly worth wrapping a try/catch in the email send?
