### ISSUE TITLE
TupleParameter errors in dynamic dependencies

### ISSUE THREAD

**Issue by duckontheweb** [spotify/luigi#2609]
Passing a `TupleParameter` in a dynamic dependency results in a `TypeError` in Python 3.6.5. See the following example for a basic demonstration.

The following code:

```python
import luigi
import luigi.mock
import luigi.util

class FirstTask(luigi.Task):

    # my_tuple = luigi.ListParameter(default=(1, 2, 3))
    my_tuple = luigi.TupleParameter(default=(1, 2, 3))

    @property
    def tuple_string(self):
        return '-'.join(map(str, self.my_tuple))

    def run(self):
        print(self.task_id + ': ' + self.tuple_string)
        with self.output().open('w') as f:
            f.write(self.tuple_string)

    def output(self):
        return luigi.mock.MockTarget(self.task_id)


@luigi.util.inherits(FirstTask)
class SecondTask(luigi.Task):

    def run(self):
        input_target = yield FirstTask(my_tuple=tuple(self.my_tuple))

        with input_target.open('r') as src:
            my_tuple = src.read()
            print(self.task_id + ': ' + my_tuple)

            with self.output().open('w') as dst:
                dst.write(my_tuple)

    def output(self):
        return luigi.mock.MockTarget(self.task_id)

if __name__ == '__main__':
    luigi.build([SecondTask()], local_scheduler=True)
```

... results in this error:

```console
$ python scratch_9.py
DEBUG: Checking if SecondTask(my_tuple=[1, 2, 3]) is complete
INFO: Informed scheduler that task   SecondTask__1__2__3__a7a294ba13   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 10635] Worker Worker(salt=723375901, workers=1, host=DGJonathanDuckworth.local, username=jduckworth, pid=10635) running   SecondTask(my_tuple=[1, 2, 3])
INFO: [pid 10635] Worker Worker(salt=723375901, workers=1, host=DGJonathanDuckworth.local, username=jduckworth, pid=10635) new requirements      SecondTask(my_tuple=[1, 2, 3])
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Worker Worker(salt=723375901, workers=1, host=DGJonathanDuckworth.local, username=jduckworth, pid=10635) was stopped. Shutting down Keep-Alive thread
Traceback (most recent call last):
  File "/Users/jduckworth/Library/Preferences/PyCharmCE2018.3/scratches/scratch_9.py", line 40, in <module>
    luigi.build([SecondTask()], local_scheduler=True)
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/interface.py", line 274, in build
    return _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)['success']
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/interface.py", line 207, in _schedule_and_run
    success &= worker.run()
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/worker.py", line 1162, in run
    self._handle_next_task()
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/worker.py", line 1066, in _handle_next_task
    for module, name, params in new_requirements]
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/worker.py", line 1066, in <listcomp>
    for module, name, params in new_requirements]
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/task_register.py", line 253, in load_task
    return task_cls.from_str_params(params_str)
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/task.py", line 482, in from_str_params
    kwargs[param_name] = param.parse(param_str)
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/parameter.py", line 1107, in parse
    return tuple(tuple(x) for x in json.loads(x, object_pairs_hook=_FrozenOrderedDict))
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/parameter.py", line 1107, in <genexpr>
    return tuple(tuple(x) for x in json.loads(x, object_pairs_hook=_FrozenOrderedDict))
TypeError: 'int' object is not iterable
```

It looks like the problem is that the code [here](https://github.com/spotify/luigi/blob/master/luigi/parameter.py#L1117) catches a `ValueError`, but not a `TypeError`. I haven't tested in Python 2, but I'm assuming a `ValueError` gets thrown in that case and this is just a result of differences in Python versions.

I'm happy to put in a PR if it's helpful.

**Comment by dlstadther** [comment]
Hi @duckontheweb Thanks for raising this issue? I'd be happy to review a PR for this issue - just be sure to include a test which fails before the patch and passes after the patch! Thanks!
