### ISSUE TITLE
ubuntu 16.04 python 3.5 pip3  intall "invalid syntax"

### ISSUE THREAD

**Issue by smartAndgoodMark** [spotify/luigi#2632]
I guess it doesn't support python3.5, it is the default python3 version under ubuntu16.04 system.

```
Collecting python-daemon<1.7,>=1.6 (from luiti)
  Downloading https://files.pythonhosted.org/packages/b8/e2/bd862c723451121f41cf53d87a9f2c69eeb97358fb4477b929878804b8a3/python-daemon-1.6.1.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vpyz80sz/python-daemon/setup.py", line 24, in <module>
        main_module = __import__(main_module_name, fromlist=[b'version'])
      File "/tmp/pip-build-vpyz80sz/python-daemon/daemon/__init__.py", line 42, in <module>
        from . import version
      File "/tmp/pip-build-vpyz80sz/python-daemon/daemon/version/__init__.py", line 17, in <module>
        from .version_info import version_info
      File "/tmp/pip-build-vpyz80sz/python-daemon/daemon/version/version_info.py", line 20
        print 'revision: %(revno)s' % version_info
                                  ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vpyz80sz/python-daemon/

```

**Comment by smartAndgoodMark** [comment]
I am a bit silly and confused, and my IQ is not online at the moment. It seems that with the power of Luigi, Luiti has not been maintained, thank you again for your answer.
