### ISSUE TITLE
Debugging luigi in an IDE

### ISSUE THREAD

**Issue by veltzerdoron** [spotify/luigi#2690]
For some reason in my IDE (pycharm) luigi can't be debugged when the tasks and the luigi.run invocation are in the same module, otherwise I get the following exception from pydev:

> ERROR: Luigi unexpected framework error while scheduling HelloWorldTask(ident=ide, path=hello_world_files)
Traceback (most recent call last):
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\worker.py", line 740, in add
    current = queue.get()
  File "<string>", line 2, in get
  File "c:\program files\python36\Lib\multiprocessing\managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "c:\program files\python36\Lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'HelloWorldTask' on <module 'pydevd' from 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2018.3\\helpers\\pydev\\pydevd.py'>
INFO: Worker Worker(salt=339097217, workers=4, host=TLVCMEN000134, username=doroni, pid=10808) was stopped. Shutting down Keep-Alive thread
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3\helpers\pydev\pydevd.py", line 1689, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3\helpers\pydev\pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3\helpers\pydev\pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/dv90863/git/mario/demos/hello_world_demo.py", line 82, in <module>
    main_task_cls=HelloWorldTask)
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\interface.py", line 192, in run
    return _run(*args, **kwargs)['success']
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\interface.py", line 209, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\interface.py", line 170, in _schedule_and_run
    success &= worker.add(t, env_params.parallel_scheduling, env_params.parallel_scheduling_processes)
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\worker.py", line 740, in add
    current = queue.get()
  File "<string>", line 2, in get
  File "c:\program files\python36\Lib\multiprocessing\managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "c:\program files\python36\Lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'HelloWorldTask' on <module 'pydevd' from 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2018.3\\helpers\\pydev\\pydevd.py'>

**Comment by mattseymour** [comment]
Got some example code?

**Comment by veltzerdoron** [comment]
Sorry, I didn't notice your reply, this is about as simple I could get it down to:

`import luigi


class HelloWorldTask(luigi.Task):
    def run(self):
        with open(self.output().path, 'w') as output_file:
            content = '{} {}!'.format("hello", "world")
            output_file.write(content)
            output_file.close()

    def output(self):
        return luigi.LocalTarget('hello_world.txt')

    def requires(self):
        return []


if __name__ == '__main__':
    luigi.run(["HelloWorldTask"])`

Taking the luigi.run to a different main.py file which imports this one will make debug run but running it as it is under the pycharm IDE gives the same exception, including it here again:

> ERROR: Luigi unexpected framework error while scheduling HelloWorldTask()
Traceback (most recent call last):
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\worker.py", line 740, in add
    current = queue.get()
  File "<string>", line 2, in get
  File "c:\program files\python36\Lib\multiprocessing\managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "c:\program files\python36\Lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'HelloWorldTask' on <module 'pydevd' from 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2018.3\\helpers\\pydev\\pydevd.py'>
INFO: Worker Worker(salt=676892175, workers=1, host=TLVCMEN000134, username=doroni, pid=8500) was stopped. Shutting down Keep-Alive thread
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3\helpers\pydev\pydevd.py", line 1689, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3\helpers\pydev\pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3\helpers\pydev\pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/dv90863/git/mario/demos/hello_world_demo_files2/hello_world_demo.py", line 19, in <module>
    luigi.run(["HelloWorldTask"])
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\interface.py", line 192, in run
    return _run(*args, **kwargs)['success']
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\interface.py", line 209, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\interface.py", line 170, in _schedule_and_run
    success &= worker.add(t, env_params.parallel_scheduling, env_params.parallel_scheduling_processes)
  File "C:\Users\dv90863\py3_6_mario\lib\site-packages\luigi\worker.py", line 740, in add
    current = queue.get()
  File "<string>", line 2, in get
  File "c:\program files\python36\Lib\multiprocessing\managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "c:\program files\python36\Lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'HelloWorldTask' on <module 'pydevd' from 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2018.3\\helpers\\pydev\\pydevd.py'>

**Comment by maksimt** [comment]
Not sure what your error was; I am able to attach a debugger inside the `run` method using PyCharm 2019.2. I had to modify your code to use `luigi.build` instead:

```python
import luigi
class HelloWorldTask(luigi.Task):
    def run(self):
        with open(self.output().path, 'w') as output_file:
            content = '{} {}!'.format("hello", "world")
            output_file.write(content)
            output_file.close()
    def output(self):
        return luigi.LocalTarget('hello_world.txt')
    def requires(self):
        return []

if __name__ == '__main__':
    luigi.build([HelloWorldTask()], local_scheduler=True)
```
