### ISSUE TITLE
Serialization csv file with pandas.DataFrame.to_csv and luigi.format.Gzip (python 3)

### ISSUE THREAD

**Issue by Kim2212** [spotify/luigi#2719]
python=3.7
luigi=2.8.0
pandas=0.24.2

Luigi Task fails, when serializing pandas.DataFrame to csv file with gzip compression
```
Traceback (most recent call last):
  File "/home/vladimir/pyt3.7/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/home/vladimir/pyt3.7/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
    task_gen = self.task.run()
  File "simple_task.py", line 15, in run
    df.to_csv(ofile, index=False, compression='gzip')
  File "/home/vladimir/pyt3.7/lib/python3.7/site-packages/pandas/core/generic.py", line 3020, in to_csv
    formatter.save()
  File "/home/vladimir/pyt3.7/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 172, in save
    self._save()
  File "/home/vladimir/pyt3.7/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 274, in _save
    self._save_header()
  File "/home/vladimir/pyt3.7/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 242, in _save_header
    writer.writerow(encoded_labels)
  File "/home/vladimir/pyt3.7/lib/python3.7/site-packages/luigi/format.py", line 188, in write
    self._process.stdin.write(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

codes:
```
import luigi
import pandas as pd
import numpy as np


class SimpleTask(luigi.Task):

    def output(self):
        return luigi.LocalTarget('result.csv.gz', format=luigi.format.Gzip)

    def run(self):
        df = pd.DataFrame(np.random.randn(100, 3), columns=['a', 'b', 'c'])

        with self.output().open('w') as ofile:
            df.to_csv(ofile, index=False, compression='gzip')

if __name__ == '__main__':
    luigi.run()
```
works fine if add this `args = tuple(arg.encode('utf-8') if type(arg) == str else arg for arg in args)` [here](https://github.com/spotify/luigi/blob/2de1b686d14e4c3d844d1eaca62405b8256fdd3f/luigi/format.py#L187)

**Comment by Kim2212** [comment]
Found solution [here](https://github.com/pandas-dev/pandas/issues/19827)
