### ISSUE TITLE
Uncaught exception in execution summary 

### ISSUE THREAD

**Issue by orenovadia** [spotify/luigi#2729]
While generating an execution summary, `current_task._requires()` is called without any exception protection.

In case a pending task fails on a later call to `_requires()`  (say some external service died while luigi was running), an exception is thrown and is not handled. 

These tasks reproduce the issue:
```python
from luigi.target import Target
from luigi.task import ExternalTask, WrapperTask


class MissingExternal(ExternalTask):
    # this task is pending: missing external dependency
    def output(self):
        class DoesNotExist(Target):

            def exists(self):
                return False

        return DoesNotExist()


class MyTask(WrapperTask):
    # This task is left pending due to MissingExternal
    # But it will make execution summary crash later on
    num_calls = 0

    def requires(self):
        if self.num_calls == 2:
            raise Exception('Crash in a later call to requires()')
        self.num_calls += 1
        yield MissingExternal()
```

Running it yields:
```bash
ERROR: Uncaught exception in luigi
Traceback (most recent call last):
  File "luigi/retcodes.py", line 75, in run_with_retcodes
    worker = luigi.interface._run(argv).worker
  File "luigi/interface.py", line 211, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "luigi/interface.py", line 174, in _schedule_and_run
    luigi_run_result = LuigiRunResult(worker, success)
  File "luigi/execution_summary.py", line 78, in __init__
    summary_dict = _summary_dict(worker)
  File "luigi/execution_summary.py", line 393, in _summary_dict
    _populate_unknown_statuses(set_tasks)
  File "luigi/execution_summary.py", line 131, in _populate_unknown_statuses
    _depth_first_search(set_tasks, task, visited)
  File "luigi/execution_summary.py", line 144, in _depth_first_search
    for task in current_task._requires():
  File "luigi/task.py", line 626, in _requires
    return flatten(self.requires())  # base impl
  File "luigi/task.py", line 887, in flatten
    for result in iterator:
  File "fizz.py", line 23, in requires
    raise Exception('Crash in a later call to requires()')
Exception: Crash in a later call to requires()
```

**Comment by dlstadther** [comment]
@orenovadia  We would welcome a PR to resolve this bug :) All are welcome to contribute! Thanks!

**Comment by Tarrasch** [comment]
This is not a bug. `requires()` shouldn't have side effects (unlike say `complete()` which of course may)

**Comment by orenovadia** [comment]
Hi @Tarrasch , If by side effect you mean that I am incrementing a counter then of course you are right.
But it's just a simulation: a real scenario is that `requires()` fails to communicate with an external service for example.

**Comment by Tarrasch** [comment]
> communicate with an external service

That's a side effect as you know. But if you know of a clever way to make the handling of this better that would be great.
