### ISSUE TITLE
luigi.task_register.TaskClassAmbigiousException: Task 'Streams' is ambiguous

### ISSUE THREAD

**Issue by kashifusmani** [spotify/luigi#2737]
I am following a minimal example from https://luigi.readthedocs.io/en/stable/example_top_artists.html

```
class Streams(luigi.Task):
    """
    Faked version right now, just generates bogus data.
    """
    date = luigi.DateParameter()


    def run(self):
        """
        Generates bogus data and writes it into the :py:meth:`~.Streams.output` target.
        """
        with self.output().open('w') as output:
            for _ in range(1000):
                output.write('{} {} {}\n'.format(
                    random.randint(0, 999),
                    random.randint(0, 999),
                    random.randint(0, 999)))

    def output(self):
        """
        Returns the target output for this task.
        In this case, a successful execution of this task will create a file in the local file system.

        :return: the target output for this task.
        :rtype: object (:py:class:`luigi.target.Target`)
        """
        return luigi.LocalTarget(self.date.strftime('data/streams_%Y_%m_%d_faked.tsv'))
```

The above code, when run gives me the error that ```luigi.task_register.TaskClassAmbigiousException: Task 'Streams' is ambiguous```

I need to understand what am I missing? I am running it via IntelliJ with the configuration
```--module my_script Streams --local-scheduler --date-interval 2012-06```

If I run it from terminal, it works. Not sure what is missing when its run via IntelliJ?

Is there a way I can set the task name?

The following in the complete stack trace

```
Traceback (most recent call last):
  File "/Users/kusmani/Library/Application Support/IntelliJIdea2018.1/python/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Users/kusmani/Library/Application Support/IntelliJIdea2018.1/python/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/kusmani/Library/Application Support/IntelliJIdea2018.1/python/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/kusmani/Library/Application Support/IntelliJIdea2018.1/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/kusmani/Projects/luigi/luigi_task/code/my_script.py", line 87, in <module>
    luigi.run()
  File "/Users/kusmani/Projects/virts/luigi/lib/python3.7/site-packages/luigi/interface.py", line 194, in run
    luigi_run_result = _run(*args, **kwargs)
  File "/Users/kusmani/Projects/virts/luigi/lib/python3.7/site-packages/luigi/interface.py", line 210, in _run
    with CmdlineParser.global_instance(cmdline_args) as cp:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/kusmani/Projects/virts/luigi/lib/python3.7/site-packages/luigi/cmdline_parser.py", line 52, in global_instance
    new_value = CmdlineParser(cmdline_args)
  File "/Users/kusmani/Projects/virts/luigi/lib/python3.7/site-packages/luigi/cmdline_parser.py", line 76, in __init__
    Register.get_task_cls(root_task)
  File "/Users/kusmani/Projects/virts/luigi/lib/python3.7/site-packages/luigi/task_register.py", line 182, in get_task_cls
    raise TaskClassAmbigiousException('Task %r is ambiguous' % name)
luigi.task_register.TaskClassAmbigiousException: Task 'Streams' is ambiguous```

**Comment by kashifusmani** [comment]
Follow at https://groups.google.com/forum/#!topic/luigi-user/5gxWGOhHuPk
