### ISSUE TITLE
Dynamically importing modules while using dynamic dependencies results in ambiguous task name

### ISSUE THREAD

**Issue by ihowell** [spotify/luigi#2775]
When I import a module dynamically and that module uses dynamic dependencies, luigi registers the task classes twice, resulting in an ambiguous class name. I've created this minimal use case to reproduce the bug:

```
# main.py
import luigi
import importlib.util
import sys


def main():
    spec = importlib.util.spec_from_file_location("workflow", "workflow.py")
    workflow = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(workflow)

    workflows = [workflow.Workflow()]
    luigi.build(workflows, workers=1, local_scheduler=True)


if __name__ == '__main__':
    print(sys.argv)
    main()
```

```
# workflow.py
import luigi


class TaskOne(luigi.Task):
    def output(self):
        return luigi.LocalTarget("out.txt")

    def run(self):
        with self.output().open("w") as out_file:
            out_file.write("Hello World!")


class Workflow(luigi.Task):
    def output(self):
        return luigi.LocalTarget("workflow.success")

    def run(self):
        yield TaskOne()
        with self.output().open("w") as success_file:
            success_file.write("1")
```

By running `python main.py`, I get this stack trace:

```
DEBUG: Checking if Workflow() is complete
INFO: Informed scheduler that task   Workflow__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 6040] Worker Worker(salt=970405691, workers=1, host=cse-yu-12.local, username=ihowell, pid=6040) running   Workflow()
INFO: [pid 6040] Worker Worker(salt=970405691, workers=1, host=cse-yu-12.local, username=ihowell, pid=6040) new requirements      Workflow()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Worker Worker(salt=970405691, workers=1, host=cse-yu-12.local, username=ihowell, pid=6040) was stopped. Shutting down Keep-Alive thread
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    main()
  File "main.py", line 12, in main
    luigi.build(workflows, workers=1, local_scheduler=True)
  File "/Users/ihowell/.venvs/luigi/lib/python3.7/site-packages/luigi/interface.py", line 237, in build
    luigi_run_result = _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)
  File "/Users/ihowell/.venvs/luigi/lib/python3.7/site-packages/luigi/interface.py", line 173, in _schedule_and_run
    success &= worker.run()
  File "/Users/ihowell/.venvs/luigi/lib/python3.7/site-packages/luigi/worker.py", line 1192, in run
    self._handle_next_task()
  File "/Users/ihowell/.venvs/luigi/lib/python3.7/site-packages/luigi/worker.py", line 1088, in _handle_next_task
    for module, name, params in new_requirements]
  File "/Users/ihowell/.venvs/luigi/lib/python3.7/site-packages/luigi/worker.py", line 1088, in <listcomp>
    for module, name, params in new_requirements]
  File "/Users/ihowell/.venvs/luigi/lib/python3.7/site-packages/luigi/task_register.py", line 252, in load_task
    task_cls = Register.get_task_cls(task_name)
  File "/Users/ihowell/.venvs/luigi/lib/python3.7/site-packages/luigi/task_register.py", line 182, in get_task_cls
    raise TaskClassAmbigiousException('Task %r is ambiguous' % name)
luigi.task_register.TaskClassAmbigiousException: Task 'TaskOne' is ambiguous
```

**Comment by Tarrasch** [comment]
Luigi now supports automatic namespacing which might resolve this issue.

**Comment by SumedhaZestl** [comment]
@Tarrasch , we have been facing the ambiguous task  issue since one month.
We have written 2 task(class and subclass) and trying to execute them with different input.
Also,we have added the luigi.auto_namespacing() in top most __init__.py
**But on same input it's working as expected but if we change the input its raising the following error:**

Traceback (most recent call last):
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/apple/Documents/TwigMePythonWorkspace/zvolv-automations/app/server.py", line 28, in post
    task_build_response_obj = main.build(data)
  File "/Users/apple/Documents/TwigMePythonWorkspace/zvolv-automations/app/main.py", line 37, in build
    response = luigi.build([task], local_scheduler=True)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/interface.py", line 237, in build
    luigi_run_result = _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/interface.py", line 173, in _schedule_and_run
    success &= worker.run()
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/worker.py", line 1185, in run
    self._handle_next_task()
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/worker.py", line 1080, in _handle_next_task
    new_req = [load_task(module, name, params)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/worker.py", line 1080, in <listcomp>
    new_req = [load_task(module, name, params)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/task_register.py", line 251, in load_task
    task_cls = Register.get_task_cls(task_name)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/task_register.py", line 181, in get_task_cls
    raise TaskClassAmbigiousException('Task %r is ambiguous' % name)
**luigi.task_register.TaskClassAmbigiousException: Task '1652789192_273710416_1652789192testsimplebot.MainTask' is ambiguous**


We have built an API base interface which will execute the luigi tasks via luigi.build.
Now we have come to the assumption that luigi maintain the state for task instances with same inputs only.
Please clarify.
