### ISSUE TITLE
Cant start luigid in background with Python 3.8

### ISSUE THREAD

**Issue by christophesaintjean** [spotify/luigi#2886]
After a recent update (luigi and system), i got the following error:
"""
**$ pip install --user --upgrade luigi**
....
...
Successfully installed luigi-2.8.11

**$ luigid --background --logdir ~/logs**
Traceback (most recent call last):
  File "/home/csaintje/.local/bin/luigid", line 8, in <module>
    sys.exit(luigid())
  File "/home/csaintje/.local/lib/python3.8/site-packages/luigi/cmdline.py", line 33, in luigid
    luigi.process.daemonize(luigi.server.run, api_port=opts.port,
  File "/home/csaintje/.local/lib/python3.8/site-packages/luigi/process.py", line 101, in daemonize
    ctx = daemon.DaemonContext(
  File "/home/csaintje/.local/lib/python3.8/site-packages/daemon/daemon.py", line 280, in __init__
    detach_process = is_detach_process_context_required()
  File "/home/csaintje/.local/lib/python3.8/site-packages/daemon/daemon.py", line 801, in is_detach_process_context_required
    if is_process_started_by_init() or is_process_started_by_superserver():
  File "/home/csaintje/.local/lib/python3.8/site-packages/daemon/daemon.py", line 778, in is_process_started_by_superserver
    if is_socket(stdin_fd):
  File "/home/csaintje/.local/lib/python3.8/site-packages/daemon/daemon.py", line 743, in is_socket
    file_socket = socket.fromfd(fd, socket.AF_INET, socket.SOCK_RAW)
  File "/usr/lib/python3.8/socket.py", line 544, in fromfd
    return socket(family, type, proto, nfd)
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 88] Socket operation on non-socket

**$ uname -a**
Linux delirium 4.19.97-1-MANJARO #1 SMP Sat Jan 18 00:17:24 UTC 2020 x86_64 GNU/Linux
"""

Launching it with **$ luigid --logdir ~/logs** yields no error.

**Comment by drowoseque** [comment]
@christophesaintjean 
could you please check if some other process uses luigid port 8082 ?

**Comment by christophesaintjean** [comment]
if you mean "netstat -a | grep 8082", the result is empty.

**Comment by hirolau** [comment]
A quick google search suggest that there are some changes in socket in 3.8 of Python. Would it be possible for you to run the same code using an older version of Python, and see if that works?

**Comment by christopherpryer** [comment]
> A quick google search suggest that there are some changes in socket in 3.8 of Python. Would it be possible for you to run the same code using an older version of Python, and see if that works?

I just ran into a NotImplementedError when trying to push my server to a computer with 3.8 installed. I removed 3.8 and installed 3.7.6 and it's working.

**Comment by christophesaintjean** [comment]
This is confirmed, the background option is no longer functional after the switch from python 3.7 to python 3.8.

**Comment by honnix** [comment]
https://pagure.io/python-daemon/issue/34

Seems like a depended lib issue. Thanks for reporting.

I should also point out we haven't done any test under 3.8 and Luigi doesn't officially support anything beyond 3.7.

**Comment by pybrgr** [comment]
Bumping for any recent activity. Currently have a 3.8 build that ideally shouldn't be rolled back.
