### ISSUE TITLE
inherits and requires fails with luigi.Task but does not fail with luigi.WrapperTask

### ISSUE THREAD

**Issue by nesat** [spotify/luigi#2916]
Luigi tasks requiring other luigi tasks that are created either using `luigi.util.inherits` or `luigi.util.requires` fail even the inherited tasks are finished. However, when inherited tasks are defined as `luigi.WrapperTask` instead of `luigi.Task`, the main task finishes successfully.

https://luigi.readthedocs.io/en/stable/api/luigi.util.html#luigi.util.inherits and https://luigi.readthedocs.io/en/stable/api/luigi.util.html#luigi.util.requires meant to use `luigi.util.inherits` and `luigi.util.requires` with `luigi.Task`

Am I doing something wrong or is there a bug?

### **Before sharing the example, code please note that when I edit**
```
@requires(TaskB)
class CopyTaskB(luigi.Task):
    pass


@inherits(TaskA)
class CopyTaskA(luigi.Task):
    def requires(self):
        return self.clone(TaskA)
```
### **to**
```
@requires(TaskB)
class CopyTaskB(luigi.WrapperTask):
    pass


@inherits(TaskA)
class CopyTaskA(luigi.WrapperTask):
    def requires(self):
        return self.clone(TaskA)
```
### main.py
```
import luigi
from luigi.util import inherits, requires

from task_a import TaskA
from task_b import TaskB


class MainTask(luigi.Task):
    task_namespace = "req"
    date = luigi.DateParameter()

    def requires(self):
        return [CopyTaskA(date=self.date),
                CopyTaskB(date=self.date)]


@requires(TaskB)
class CopyTaskB(luigi.Task):
    pass


@inherits(TaskA)
class CopyTaskA(luigi.Task):
    def requires(self):
        return self.clone(TaskA)


if __name__ == '__main__':
    luigi.run()
```

### task_a.py
```
import luigi


class TaskA(luigi.Task):
    task_namespace = "req"
    date = luigi.DateParameter()

    def output(self):
        return luigi.LocalTarget('./luigi_outputs/{}/{}.txt'.format(str(self.date), self.__class__.__name__))

    def run(self):
        with self.output().open('w') as f:
            f.write('Done')
```

### task_b.py
```
import luigi


class TaskB(luigi.Task):
    task_namespace = "req"
    date = luigi.DateParameter()

    def output(self):
        return luigi.LocalTarget('./luigi_outputs/{}/{}.txt'.format(str(self.date), self.__class__.__name__))

    def run(self):
        with self.output().open('w') as f:
            f.write('Done')
```

### Command line
`python3 main.py req.MainTask --date 2020-03-06 --local-scheduler`

### Error message
```
DEBUG: Checking if req.MainTask(date=2020-03-06) is complete
/xxx/luigi/lib/python3.7/site-packages/luigi/worker.py:409: UserWarning: Task req.MainTask(date=2020-03-06) without outputs has no custom complete() method
  is_complete = task.complete()
DEBUG: Checking if CopyTaskA(date=2020-03-06) is complete
/xxx/luigi/lib/python3.7/site-packages/luigi/worker.py:409: UserWarning: Task CopyTaskA(date=2020-03-06) without outputs has no custom complete() method
  is_complete = task.complete()
DEBUG: Checking if CopyTaskB(date=2020-03-06) is complete
/xxx/luigi/lib/python3.7/site-packages/luigi/worker.py:409: UserWarning: Task CopyTaskB(date=2020-03-06) without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   req.MainTask_2020_03_06_e53bc182d5   has status   PENDING
DEBUG: Checking if req.TaskB(date=2020-03-06) is complete
INFO: Informed scheduler that task   CopyTaskB_2020_03_06_e53bc182d5   has status   PENDING
INFO: Informed scheduler that task   req.TaskB_2020_03_06_e53bc182d5   has status   DONE
DEBUG: Checking if req.TaskA(date=2020-03-06) is complete
INFO: Informed scheduler that task   CopyTaskA_2020_03_06_e53bc182d5   has status   PENDING
INFO: Informed scheduler that task   req.TaskA_2020_03_06_e53bc182d5   has status   DONE
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 3
INFO: [pid 70400] Worker Worker(salt=466072318, workers=1, host=xxx, username=xxx, pid=70400) running   CopyTaskA(date=2020-03-06)
INFO: [pid 70400] Worker Worker(salt=466072318, workers=1, host=xxx, username=xxx, pid=70400) done      CopyTaskA(date=2020-03-06)
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   CopyTaskA_2020_03_06_e53bc182d5   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
INFO: [pid 70400] Worker Worker(salt=466072318, workers=1, host=xxx, username=xxx, pid=70400) running   CopyTaskB(date=2020-03-06)
INFO: [pid 70400] Worker Worker(salt=466072318, workers=1, host=xxx, username=xxx, pid=70400) done      CopyTaskB(date=2020-03-06)
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   CopyTaskB_2020_03_06_e53bc182d5   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 70400] Worker Worker(salt=466072318, workers=1, host=xxx, username=xxx, pid=70400) running   req.MainTask(date=2020-03-06)
/xxx/luigi/lib/python3.7/site-packages/luigi/worker.py:181: UserWarning: Task CopyTaskA(date=2020-03-06) without outputs has no custom complete() method
  missing = [dep.task_id for dep in self.task.deps() if not dep.complete()]
/xxx/luigi/lib/python3.7/site-packages/luigi/worker.py:181: UserWarning: Task CopyTaskB(date=2020-03-06) without outputs has no custom complete() method
  missing = [dep.task_id for dep in self.task.deps() if not dep.complete()]
ERROR: [pid 70400] Worker Worker(salt=466072318, workers=1, host=xxx, username=xxx, pid=70400) failed    req.MainTask(date=2020-03-06)
Traceback (most recent call last):
  File "/xxx/luigi/lib/python3.7/site-packages/luigi/worker.py", line 184, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependencies at run time: CopyTaskA_2020_03_06_e53bc182d5, CopyTaskB_2020_03_06_e53bc182d5
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   req.MainTask_2020_03_06_e53bc182d5   has status   FAILED
DEBUG: Checking if req.MainTask(date=2020-03-06) is complete
DEBUG: Checking if CopyTaskA(date=2020-03-06) is complete
DEBUG: Checking if CopyTaskB(date=2020-03-06) is complete
INFO: Informed scheduler that task   req.MainTask_2020_03_06_e53bc182d5   has status   PENDING
DEBUG: Checking if req.TaskB(date=2020-03-06) is complete
INFO: Informed scheduler that task   CopyTaskB_2020_03_06_e53bc182d5   has status   PENDING
INFO: Informed scheduler that task   req.TaskB_2020_03_06_e53bc182d5   has status   DONE
DEBUG: Checking if req.TaskA(date=2020-03-06) is complete
INFO: Informed scheduler that task   CopyTaskA_2020_03_06_e53bc182d5   has status   PENDING
INFO: Informed scheduler that task   req.TaskA_2020_03_06_e53bc182d5   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 70400] Worker Worker(salt=466072318, workers=1, host=xxx, username=xxx, pid=70400) running   req.MainTask(date=2020-03-06)
ERROR: [pid 70400] Worker Worker(salt=466072318, workers=1, host=xxx, username=xxx, pid=70400) failed    req.MainTask(date=2020-03-06)
Traceback (most recent call last):
  File "/xxx/luigi/lib/python3.7/site-packages/luigi/worker.py", line 184, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependencies at run time: CopyTaskA_2020_03_06_e53bc182d5, CopyTaskB_2020_03_06_e53bc182d5
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   req.MainTask_2020_03_06_e53bc182d5   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 1 pending tasks possibly being run by other workers
DEBUG: There are 1 pending tasks unique to this worker
DEBUG: There are 1 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=466072318, workers=1, host=xxx, username=xxx, pid=70400) was stopped. Shutting down Keep-Alive thread
INFO:
===== Luigi Execution Summary =====

Scheduled 5 tasks of which:
* 2 complete ones were encountered:
    - 1 req.TaskA(date=2020-03-06)
    - 1 req.TaskB(date=2020-03-06)
* 2 ran successfully:
    - 1 CopyTaskA(date=2020-03-06)
    - 1 CopyTaskB(date=2020-03-06)
* 1 failed:
    - 1 req.MainTask(date=2020-03-06)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====


Process finished with exit code 0

```

Luigi version: 2.8.11
May be related to https://github.com/spotify/luigi/issues/1552

**Main goal [out of topic]:** I want to import luigi tasks from python packages and reuse them. However, some of the imported luigi tasks depend to some of the other imported luigitasks. In the example, I did not show that but in the end I will edit my code as:
```
@inherits(TaskA)
class CopyTaskA(luigi.Task):
    def requires(self):
        return [CopyTaskB(date=self.date), self.clone(TaskA)]
```

**Comment by drj42** [comment]
The tasks are failing because they don't have an `output()` method defined, and so there's no way for luigi to determine if the task completes or not. 

The `inherits` and `requires` decorators won't do actual python inheritance, they just monkeypatch the target class with the same parameter attributes of another class.  And in the case of `requires`, it will also monkeypatch a `requires()` method to the task class, but that is it.

WrapperTasks are a special case task class that comes with a custom `complete()` method, that simply calls `complete()` on all of its dependencies, and doesn't have an output of its own.   That's why your tasks that only define a `requires` method succeed as WrapperTasks.

So I think this is behaving as expected.

**Comment by nesat** [comment]
@drj42 thank you very much. Maybe it is out of topic but is there a problem using pythonic inheritence? As far as I understand, luigi `inherits` decorator copies only the luigi parameter. Should I use luigi inherits also when I use pythonic inheritence? Actually what I try to do is copying the imported luigi task and add an additional requirement task. I searched in documentation, example codes, issues even in google groups but could not find any example.

**Comment by drj42** [comment]
Your case sounds like it would be best with a subclass that overrides requires(), since you are using it as a kind of base class.  All attributes and methods will be inherited, so you don't need to use the decorators there.

The decorators come in handy when want to share common luigi parameters among tasks that have different base task classes, and so you don't want them to inherit from one another.  

Normally, the pythonic thing to do in that kind of situation, might be to define a mixin with the common parameters and use multiple inheritance, but... luigi parameters can only initialize properly on subclass of luigi.Task (because of metaclass magic or something).  So the mixin itself has to be derived from a luigi task class too.  And its usually a big can of worms to inherit directly from multiple luigi task classes.

**Comment by joooeey** [comment]
Does that mean it's generally a bad idea to use the Mixin pattern with Luigi?
