### ISSUE TITLE
[Question] What should be the value of --address arg for luigid

### ISSUE THREAD

**Issue by tashrifbillah** [spotify/luigi#2979]
Hi all,

What should be the value of `--address` arg for `luigid` when launching the server? I tried many things-- http://localhost, http://127.0.0.1, etc. but they all result in the following error:
> (base) [tb571@pnl-z840-2 luigi-pnlpipe]$ luigid --port 8083 --logdir luigi-server.log/ --address http://localhost
```vim
Traceback (most recent call last):
  File "/home/tb571/miniconda3/bin/luigid", line 11, in <module>
    sys.exit(luigid())
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/luigi/cmdline.py", line 37, in luigid
    luigi.server.run(api_port=opts.port, address=opts.address, unix_socket=opts.unix_socket)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/luigi/server.py", line 341, in run
    unix_socket=unix_socket,
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/luigi/server.py", line 319, in _init_api
    api_sockets = tornado.netutil.bind_sockets(api_port, address=address)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/tornado/netutil.py", line 122, in bind_sockets
    0, flags)):
  File "/home/tb571/miniconda3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

I understand that the `default-scheduler-url` is http://localhost:8082 but I need to change the IP address for my localhost so asking.

**Comment by tashrifbillah** [comment]
Just `localhost` or `127.0.0.1` works.
