### ISSUE TITLE
import luigui ---> syntax error ---> VS Code

### ISSUE THREAD

**Issue by gh-reshad** [spotify/luigi#3039]
I have installed Luigi package and when I try to run the code it gives me this error:

import luigi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\luigi\__init__.py", line 23, in <module>
    from luigi import task
  File "C:\Python27\lib\site-packages\luigi\task.py", line 145
    class Task(metaclass=Register):
                        ^
SyntaxError: invalid syntax

could someone help me with this issue? I am using python 2.7 on a windows machine.

_Originally posted by @charlietianx in https://github.com/spotify/luigi/issues/1869#issuecomment-757548884_

**Comment by gh-reshad** [comment]
fixed the issue by installing older version of Luigi. (pip install luigi==2.8.9)
