### ISSUE TITLE
value error creating uncaught exception

### ISSUE THREAD

**Issue by GeorgeP2** [spotify/luigi#3100]
ERROR: Uncaught exception in luigi
Traceback (most recent call last):
  File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\retcodes.py", line 75, in run_with_retcodes
    worker = luigi.interface._run(argv).worker
  File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\interface.py", line 211, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\interface.py", line 149, in _schedule_and_run
    not(lock.acquire_for(env_params.lock_pid_dir, env_params.lock_size, kill_signal))):
  File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\lock.py", line 111, in acquire_for
    pids = {pid for pid in _read_pids_file(pid_file) if getpcmd(pid) == my_cmd}
  File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\lock.py", line 111, in <setcomp>
    pids = {pid for pid in _read_pids_file(pid_file) if getpcmd(pid) == my_cmd}
  File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\lock.py", line 42, in getpcmd
    _, val = lines
ValueError: not enough values to unpack (expected 2, got 1)

Hi The above error was started yesterday and I'm not entirely sure of the cause. Luigi was not updated and was working perfectly fine in the morning. Let me know if more details are required

**Comment by tleedepriest** [comment]
> ERROR: Uncaught exception in luigi Traceback (most recent call last): File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\retcodes.py", line 75, in run_with_retcodes worker = luigi.interface._run(argv).worker File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\interface.py", line 211, in _run return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory) File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\interface.py", line 149, in _schedule_and_run not(lock.acquire_for(env_params.lock_pid_dir, env_params.lock_size, kill_signal))): File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\lock.py", line 111, in acquire_for pids = {pid for pid in _read_pids_file(pid_file) if getpcmd(pid) == my_cmd} File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\lock.py", line 111, in pids = {pid for pid in _read_pids_file(pid_file) if getpcmd(pid) == my_cmd} File "C:\Users\priestleyg\Anaconda3\lib\site-packages\luigi\lock.py", line 42, in getpcmd _, val = lines ValueError: not enough values to unpack (expected 2, got 1)
> 
> Hi The above error was started yesterday and I'm not entirely sure of the cause. Luigi was not updated and was working perfectly fine in the morning. Let me know if more details are required

Did anyone ever figure this out? This just happened to me and seems to be non-deterministic.

**Comment by tleedepriest** [comment]
So, for more information about this error. I was working with someone on a Remote Desktop Computer, so I wasn't sure if this was caused by them running the same Task. I noticed the error came from lock.py, and when looking at the description of the source code...it was to prevent workers from running the same workflow? I simply renamed my Task ( In this case from RunAll to Run) and it the error went away and my pipeline ran.
