### ISSUE TITLE
Ambiguous task error on executing the same tasks with different inputs

### ISSUE THREAD

**Issue by SumedhaZestl** [spotify/luigi#3166]
We have been facing the ambiguous task  issue since one month.
We have written 2 task(class and subclass) and trying to execute them with different input.
Also,we have added the luigi.auto_namespacing() in top most __init__.py
**But on same input it's working as expected but if we change the input its raising the following error:**

Traceback (most recent call last):
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/apple/Documents/TwigMePythonWorkspace/zvolv-automations/app/server.py", line 28, in post
    task_build_response_obj = main.build(data)
  File "/Users/apple/Documents/TwigMePythonWorkspace/zvolv-automations/app/main.py", line 37, in build
    response = luigi.build([task], local_scheduler=True)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/interface.py", line 237, in build
    luigi_run_result = _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/interface.py", line 173, in _schedule_and_run
    success &= worker.run()
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/worker.py", line 1185, in run
    self._handle_next_task()
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/worker.py", line 1080, in _handle_next_task
    new_req = [load_task(module, name, params)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/worker.py", line 1080, in <listcomp>
    new_req = [load_task(module, name, params)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/task_register.py", line 251, in load_task
    task_cls = Register.get_task_cls(task_name)
  File "/Users/apple/.pyenv/versions/3.9.2/lib/python3.9/site-packages/luigi/task_register.py", line 181, in get_task_cls
    raise TaskClassAmbigiousException('Task %r is ambiguous' % name)
**luigi.task_register.TaskClassAmbigiousException: Task '1652789192_273710416_1652789192testsimplebot.MainTask' is ambiguous**

We have built an API base interface which will execute the luigi tasks via luigi.build.
Now we have came to the assumption that luigi maintain the state for task instances with same inputs only.
Please clarify.

**Comment by lallea** [comment]
The error indicates that you have previously created a class with the same name. I think that under some circumstances, that might be ok, but you cannot then instantiate those task classes by name. Even if you don't do that explicitly, it seems to me like it might happen implicitly as the DAG is built.

I suggest that you try to ensure that all tasks have a unique name. I think you will avoid trouble that way.
