### ISSUE TITLE
History does not work with latest luigi and sqlalchemy

### ISSUE THREAD

**Issue by tashrifbillah** [spotify/luigi#3320]
I have the latest Luigi and sqlalchemy:

```python
>>> import luigi
>>> luigi.__version__
'3.5.2'
>>> import sqlalchemy
>>> sqlalchemy.__version__
'2.0.34'

```

But history does not work for this combination. If I have this in my `luigi.cfg`:

```cfg
[scheduler]
record_task_history = True
state_path = ${HOME}/luigi-state.pickle

[task_history]
db_connection = sqlite:///${HOME}/luigi-task-hist.db
```

Then, this error is raised:

> luigid

```python
Traceback (most recent call last):
  File "/path/to/miniconda3/envs/pnlpipe9/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    meth = statement._execute_on_connection
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/miniconda3/envs/pnlpipe9/bin/luigid", line 8, in <module>
    sys.exit(luigid())
             ^^^^^^^^
  File "/path/to/miniconda3/envs/pnlpipe9/lib/python3.12/site-packages/luigi/cmdline.py", line 37, in luigid
    luigi.server.run(api_port=opts.port, address=opts.address, unix_socket=opts.unix_socket)
  File "/path/to/miniconda3/envs/pnlpipe9/lib/python3.12/site-packages/luigi/server.py", line 342, in run 
    scheduler = Scheduler()
                ^^^^^^^^^^^
  File "/path/to/miniconda3/envs/pnlpipe9/lib/python3.12/site-packages/luigi/scheduler.py", line 688, in __init__
    self._task_history = db_task_history.DbTaskHistory()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/envs/pnlpipe9/lib/python3.12/site-packages/luigi/db_task_history.py", line 86, in __init__
    _upgrade_schema(self.engine)
  File "/path/to/miniconda3/envs/pnlpipe9/lib/python3.12/site-packages/luigi/db_task_history.py", line 271, in _upgrade_schema
    for i in conn.execute('PRAGMA table_info(task_parameters);').fetchall():
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/envs/pnlpipe9/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    raise exc.ObjectNotExecutableError(statement) from err 
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'PRAGMA table_info(task_parameters);'
```

---

Question: Does anyone know which combination of luigid and sqlalchemy would work?

**Comment by tashrifbillah** [comment]
Crediting my answer to https://stackoverflow.com/a/75464429/11932012, I fixed this issue by:

> pip install sqlalchemy==1.4.54
