### ISSUE TITLE
AttributeError: 'float' object has no attribute 'last_active'

### ISSUE THREAD

**Issue by rantav** [spotify/luigi#341]
This seems to be a regression added recently. 
When I installed a version from HEAD I see these errors in the log:

```
2014-06-02 10:49:57,209 tornado.access[18581] ERROR: 500 GET /api/ping?data=%7B%22worker%22%3A+%22worker-057048904%22%7D (y-y-y-y) 1.08ms
2014-06-02 10:49:58,211 tornado.application[18581] ERROR: Uncaught exception GET /api/ping?data=%7B%22worker%22%3A+%22worker-389063243%22%7D (10.236.192.23)
HTTPRequest(protocol='http', host='ip-x-x-x-x.ec2.internal:8082', method='GET', uri='/api/ping?data=%7B%22worker%22%3A+%22worker-389063243%22%7D', version='HTTP/1.1', remote_ip='y-y-y-y', headers={'Host': 'ip-x-x-x-x.ec2.internal:8082', 'User-Agent': 'Python-urllib/2.7', 'Connection': 'close', 'Accept-Encoding': 'identity'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1218, in _when_complete
    callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1239, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/usr/local/lib/python2.7/dist-packages/luigi-1.0.16-py2.7.egg/luigi/server.py", line 60, in get
    result = getattr(self._api, method)(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/luigi-1.0.16-py2.7.egg/luigi/rpc.py", line 138, in ping
    return self._scheduler.ping(worker)
  File "/usr/local/lib/python2.7/dist-packages/luigi-1.0.16-py2.7.egg/luigi/scheduler.py", line 250, in ping
    self.update(worker)
  File "/usr/local/lib/python2.7/dist-packages/luigi-1.0.16-py2.7.egg/luigi/scheduler.py", line 167, in update
    worker.last_active = time.time()
AttributeError: 'float' object has no attribute 'last_active'
```

**Comment by Tarrasch** [comment]
Old regression ==> closing
