### ISSUE TITLE
Issues running tests

### ISSUE THREAD

**Issue by erikbern** [spotify/luigi#380]
I'm seeing some issues with the unit tests on my local computer:

```
$ nosetests test/parameter_test.py
DEBUG: Checking if Baz(bool=False) is complete
/Users/erikbern/luigi-param-refactoring/luigi/task.py:417: UserWarning: Task Baz(bool=False) without outputs has no custom complete() method
  warnings.warn("Task %r without outputs has no custom complete() method" % self)
INFO: Scheduled Baz(bool=False)
INFO: Done scheduling tasks
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 25674] Worker Worker(salt=953179801, host=Eriks-MacBook-Air.local, username=erikbern, pid=25674) running   Baz(bool=False)
INFO: [pid 25674] Worker Worker(salt=953179801, host=Eriks-MacBook-Air.local, username=erikbern, pid=25674) done      Baz(bool=False)
DEBUG: Asking scheduler for work...
INFO: Done
INFO: There are no more tasks to run at this time
INFO: Worker Worker(salt=953179801, host=Eriks-MacBook-Air.local, username=erikbern, pid=25674) was stopped. Shutting down Keep-Alive thread
.E.E..INFO: Loaded []
EE.EEE.E..EE....INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
..INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
..INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
.INFO: Loaded []
..
======================================================================
ERROR: test_bool_true (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 157, in test_bool_true
    luigi.run(['--local-scheduler', 'Baz', '--bool'])
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_default_param_cmdline (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 170, in test_default_param_cmdline
    luigi.run(['--local-scheduler', 'WithDefault'])
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_forgot_param_in_dep (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/helpers.py", line 30, in wrapper
    return fun(*args, **kwargs)
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 166, in test_forgot_param_in_dep
    luigi.run(['--local-scheduler', 'ForgotParamDep'])
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
luigi-interface: INFO: Loaded []
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_global_param_cmdline (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 179, in test_global_param_cmdline
    luigi.run(['--local-scheduler', 'HasGlobalParam', '--x', 'xyz', '--global-param', '124'])
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_global_param_dep_cmdline (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 190, in test_global_param_dep_cmdline
    luigi.run(['--local-scheduler', 'HasGlobalParamDep', '--x', 'xyz', '--global-param', '124'])
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_global_param_dep_cmdline_bool (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 202, in test_global_param_dep_cmdline_bool
    luigi.run(['--local-scheduler', 'HasGlobalParamDep', '--x', 'xyz', '--global-bool-param'])
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_global_param_dep_cmdline_optparse (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 196, in test_global_param_dep_cmdline_optparse
    luigi.run(['--local-scheduler', '--task', 'HasGlobalParamDep', '--x', 'xyz', '--global-param', '124'], use_optparse=True)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_global_param_shared (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 208, in test_global_param_shared
    luigi.run(['--local-scheduler', 'SharedGlobalParamA', '--shared-global-param', 'abc'])
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_multibool (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 145, in test_multibool
    luigi.run(['--local-scheduler', 'Bar', '--multibool', 'true', '--multibool', 'false'])
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_multibool_empty (parameter_test.ParameterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erikbern/luigi-param-refactoring/test/parameter_test.py", line 149, in test_multibool_empty
    luigi.run(['--local-scheduler', 'Bar'])
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 462, in run
    return interface.run(tasks, worker_scheduler_factory)
  File "/Users/erikbern/luigi-param-refactoring/luigi/interface.py", line 187, in run
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------
Pid(s) 25674 already running

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 45 tests in 0.467s

FAILED (errors=10)
```

**Comment by Tarrasch** [comment]
Closing because this is outdated (surely).
