### ISSUE TITLE
Luigi will sometimes reschedule broken task indefinetely

### ISSUE THREAD

**Issue by rtshadow** [spotify/luigi#412]
I've got a piece of code with task D, which will never be complete:

``` python
import luigi

class D(luigi.Task):
    def requires(self):
        return []

    def complete(self):
        return False

d = D()

class K(luigi.Task):
    def requires(self):
        return d

luigi.run(main_task_cls=K)
```

Previously in such situation, luigi would fail with `RuntimeError` and finish execution.
Now, sometimes (it does not occur on every run, so I suspect it to be some kind of race condition) if I run above code with 3 workers, I can observe luigi trying to rerun task `D` indefinetely.

Here's excerpt from logs:

```
INFO: Scheduled K() (PENDING)
DEBUG: Checking if D() is complete
INFO: Scheduled D() (PENDING)
INFO: Done scheduling tasks
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
DEBUG: Asking scheduler for work...
INFO: [pid 15449] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) running   D()
INFO: [pid 15449] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) done      D()
INFO: Done
INFO: There are no more tasks to run at this time
INFO: D() is currently run by worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445)
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
DEBUG: Asking scheduler for work...
INFO: [pid 15450] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) running   K()
ERROR: [pid 15450] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) failed    K()
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/luigi/worker.py", line 287, in _run_task
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: D()
INFO: Skipping error email. Set `error-email` in the `core` section of the luigi config file to receive error emails.
INFO: Done
INFO: There are no more tasks to run at this time
INFO: K() is currently run by worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445)
DEBUG: Checking if K() is complete
INFO: Scheduled K() (PENDING)
DEBUG: Checking if D() is complete
INFO: Scheduled D() (PENDING)
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
DEBUG: Asking scheduler for work...
INFO: [pid 15451] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) running   D()
INFO: [pid 15451] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) done      D()
INFO: Done
INFO: There are no more tasks to run at this time
INFO: D() is currently run by worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445)
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
DEBUG: Asking scheduler for work...
INFO: [pid 15452] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) running   K()
ERROR: [pid 15452] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) failed    K()
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/luigi/worker.py", line 287, in _run_task
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: D()
INFO: Skipping error email. Set `error-email` in the `core` section of the luigi config file to receive error emails.
INFO: Done
INFO: There are no more tasks to run at this time
INFO: K() is currently run by worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445)
DEBUG: Checking if K() is complete
INFO: Scheduled K() (PENDING)
DEBUG: Checking if D() is complete
INFO: Scheduled D() (PENDING)
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
DEBUG: Asking scheduler for work...
INFO: [pid 15453] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) running   D()
INFO: [pid 15453] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) done      D()
INFO: Done
INFO: There are no more tasks to run at this time
INFO: D() is currently run by worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445)
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
DEBUG: Asking scheduler for work...
INFO: [pid 15454] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) running   K()
ERROR: [pid 15454] Worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445) failed    K()
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/luigi/worker.py", line 287, in _run_task
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: D()
INFO: Skipping error email. Set `error-email` in the `core` section of the luigi config file to receive error emails.
INFO: Done
INFO: There are no more tasks to run at this time
INFO: K() is currently run by worker Worker(salt=180207888, host=wa-funnel-reprocess-8-master-0, username=root, pid=15445)
DEBUG: Checking if K() is complete
INFO: Scheduled K() (PENDING)
DEBUG: Checking if D() is complete
INFO: Scheduled D() (PENDING)
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
...

this goes on and on indefinetely
```

**Comment by themalkolm** [comment]
Ha, I just got this problem with similar log output. So maybe it is time to update our luigi version.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
