### ISSUE TITLE
Scheduler gets "stuck", tasks are running (though done) or pending (though ready) indefinitely

### ISSUE THREAD

**Issue by sportsracer** [spotify/luigi#434]
After updating to Luigi 1.0.17, our scheduler is often getting "stuck" in working through a complex task graph:
- At times, a task is not executed even though all its dependencies are met.
- Other times, a task is stuck in a "Running" state apparently, even though its output file is already present, indicating the task has run successfully.

Never had this issue before. I can resolve this by connecting to the scheduler with another worker, and re-submitting the "stuck" task. The task graph then advances, but this requires constant supervision of our Luigi scheduler ...

I have a hard time reproducing the issue, so I can't provide a code example for now. I have noticed that viewing the dependency graph of a "stuck" task fails at times with an 500 error to api/dep_graph, see also log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1042, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/luigi/server.py", line 61, in get
    result = getattr(self._api, method)(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/luigi/rpc.py", line 164, in dep_graph
    return self._scheduler.dep_graph(task_id)
  File "/usr/local/lib/python2.7/dist-packages/luigi/scheduler.py", line 357, in dep_graph
    self._recurse_deps(task_id, serialized)
...
  File "/usr/local/lib/python2.7/dist-packages/luigi/scheduler.py", line 351, in _recurse_deps
    self._recurse_deps(dep, serialized)
  File "/usr/local/lib/python2.7/dist-packages/luigi/scheduler.py", line 351, in _recurse_deps
    self._recurse_deps(dep, serialized)
  File "/usr/local/lib/python2.7/dist-packages/luigi/scheduler.py", line 345, in _recurse_deps
    'params': task.params,
AttributeError: 'NoneType' object has no attribute 'params
```

Any help would be appreciated, since it's causing us quite a few headaches. Thanks!

**Comment by Tarrasch** [comment]
Closing this pretty old ticket. I'm prettu sure it's been resolved at some point.
