### ISSUE TITLE
Occational 500 errors from server on /api/add_worker

### ISSUE THREAD

**Issue by freider** [spotify/luigi#449]
Just noticed the scheduler returning 500 errors to me and digging in the logs it seems to be an occational problem with the /api/add_worker call.

Not sure exactly which revision we are on, but it's pretty recent. Will see if I can reproduce this. Adding an issue to keep the traceback easily available if somebody else has similar problems.

```
2014-09-15 11:08:32,343 root[19579] ERROR: Uncaught exception POST /api/add_worker (192.168.100.1)
HTTPRequest(protocol='http', host='luigi_host:8082', method='POST', uri='/api/add_worker', version='HTTP/1.1', remote_ip='192.168.100.100', body='data=%7B%22info%22%3A+%5B%5B%22salt%22%2C+%22135379894%22%5D%2C+%5B%22host%22%2C+%22redacted_hostname%22%5D%2C+%5B%22username%22%2C+%22myuser%22%5D%2C+%5B%22pid%22%2C+8524%5D%5D%2C+%22worker%22%3A+%22Worker%28salt%3D135379894%2C+host%3Dredacted_hostname%2C+username%3Dmyuser%2C+pid%3D8524%29%22%7D', headers={'Content-Length': '339', 'Accept-Encoding': 'identity', 'Content-Type': 'application/x-www-form-urlencoded', 'Connection': 'close', 'Host': 'luigi_host:8082', 'User-Agent': 'Python-urllib/2.6'})
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/tornado/web.py", line 1021, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/luigi/server.py", line 62, in get
    result = getattr(self._api, method)(**arguments)
  File "/usr/lib/python2.6/dist-packages/luigi/rpc.py", line 164, in add_worker
    return self._scheduler.add_worker(worker, info)
  File "/usr/lib/python2.6/dist-packages/luigi/scheduler.py", line 227, in add_worker
    self._active_workers[worker].add_info(info)
KeyError: u'Worker(salt=135379894, host=redacted_hostname, username=myuser, pid=8524)'
2014-09-15 11:08:32,344 root[19579] ERROR: 500 POST /api/add_worker (192.168.100.1) 2.04ms
```

**Comment by Tarrasch** [comment]
Closing, I assume this is outdated by now.
