### ISSUE TITLE
Redshift: InternalError: Cannot COPY into nonexistent table

### ISSUE THREAD

**Issue by johnjiang** [spotify/luigi#586]
Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 77, in run self.task.run()
    File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/redshift.py", line 89, in run self.copy(cursor, path)
    File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/redshift.py", line 120, in copy self.copy_options))
    InternalError: Cannot COPY into nonexistent table mytable

Seems like it's not catching the InternalError exception as luigi is only looking for programming errors.

**Comment by ddaniels888** [comment]
We have code to fix this. I'll drop a pull request.

**Comment by Tarrasch** [comment]
Fixed in #702
