### ISSUE TITLE
[Critical] Travis gives green on failures

### ISSUE THREAD

**Issue by Tarrasch** [spotify/luigi#759]
Hey! I found this super serious issue. Ping @erikbern @freider @daveFNbuck @berkerpeksag. Our travis says green *regardless* if there are failures or not. See for example https://travis-ci.org/spotify/luigi/jobs/51103701 from #751. I guess this is what @daveFNbuck fixed in #752.

I'll fix this today after lunch unless anybode else wants to do this. :)

**Comment by erikbern** [comment]
that's weird!

**Comment by berkerpeksag** [comment]
Interesting, here is an example with non zero exit code: https://travis-ci.org/spotify/luigi/jobs/49392611#L371 The code looks a bit different since I was worked on it, I need to take a look first.

Just a wild guess: If you see this behavior only in "nonhdfs" tests, you can try to change NOSE_ATTR=!minicluster to NOSE_ATTR="!minicluster" in https://github.com/spotify/luigi/commit/af8f3e475a3c484b12b4bcd5a700cb8248d80253#diff-b91f3d5bd63fcd17221b267e851608e8R18

**Comment by Tarrasch** [comment]
Again I think it's a nose bug or something. It does in fact report errors when there are error. It's just that `bin_test.py` is magical or something.

It seems to behave correctly when I run the individual tests but not both (I trimmed away other tests so I can iterate faster, though the following log scales to the clean repository)

```
~/spotify/repos/luigis/github_luigi fix-travis-false-positives*  11s
❯ export PYTHONPATH=''; tox -e nonhdfs test/bin_test.pyc; echo $?  
nonhdfs develop-inst-noop: /home/arash/spotify/repos/luigis/github_luigi
nonhdfs runtests: PYTHONHASHSEED='321437419'
nonhdfs runtests: commands[0] | coverage run test/runtests.py -v test/bin_test.pyc
test_404 (bin_test.LuigidTest) ... Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/arash/spotify/repos/luigis/github_luigi/.tox/nonhdfs/local/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/arash/spotify/repos/luigis/github_luigi/test/server_test.py", line 46, in scheduler_thread
    self.run_server()
  File "/home/arash/spotify/repos/luigis/github_luigi/test/bin_test.py", line 26, in run_server
    raise Exception()
Exception

ERROR
test_404 (bin_test.ServerTest) ... ERROR

======================================================================
ERROR: test_404 (bin_test.LuigidTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arash/spotify/repos/luigis/github_luigi/test/server_test.py", line 70, in test_404
    self._test_404('/foo')
  File "/home/arash/spotify/repos/luigis/github_luigi/test/server_test.py", line 63, in _test_404
    _ = urlopen(req, timeout=10)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>

======================================================================
ERROR: test_404 (bin_test.ServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arash/spotify/repos/luigis/github_luigi/test/server_test.py", line 70, in test_404
    self._test_404('/foo')
  File "/home/arash/spotify/repos/luigis/github_luigi/test/server_test.py", line 63, in _test_404
    _ = urlopen(req, timeout=10)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
-------------------- >> begin captured logging << --------------------
luigi-interface: INFO: Loaded ['/home/arash/spotify/repos/luigis/github_luigi/test/testconfig/client.cfg']
luigi.server: INFO: No prior state file exists at /var/lib/luigi-server/state.pickle. Starting with clean slate
luigi.server: INFO: Scheduler starting up
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2 tests in 10.221s

FAILED (errors=2)
nonhdfs runtests: commands[1] | coveralls
You have to provide either repo_token in .coveralls.yml, or launch via Travis
_________________________________________________________________________________________________________________________________________ summary _________________________________________________________________________________________________________________________________________
  nonhdfs: commands succeeded
  congratulations :)
0
                                                                                                                                                                                                                                                                                           
~/spotify/repos/luigis/github_luigi fix-travis-false-positives*  11s
❯ export PYTHONPATH=''; tox -e nonhdfs test/bin_test.py:LuigidTest; echo $?
nonhdfs develop-inst-noop: /home/arash/spotify/repos/luigis/github_luigi
nonhdfs runtests: PYTHONHASHSEED='702950260'
nonhdfs runtests: commands[0] | coverage run test/runtests.py -v test/bin_test.py:LuigidTest
test_404 (bin_test.LuigidTest) ... Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/arash/spotify/repos/luigis/github_luigi/.tox/nonhdfs/local/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/arash/spotify/repos/luigis/github_luigi/test/server_test.py", line 46, in scheduler_thread
    self.run_server()
  File "/home/arash/spotify/repos/luigis/github_luigi/test/bin_test.py", line 26, in run_server
    raise Exception()
Exception

ERROR

======================================================================
ERROR: test_404 (bin_test.LuigidTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arash/spotify/repos/luigis/github_luigi/test/server_test.py", line 70, in test_404
    self._test_404('/foo')
  File "/home/arash/spotify/repos/luigis/github_luigi/test/server_test.py", line 63, in _test_404
    _ = urlopen(req, timeout=10)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>

----------------------------------------------------------------------
Ran 1 test in 0.109s

FAILED (errors=1)
ERROR: InvocationError: '/home/arash/spotify/repos/luigis/github_luigi/.tox/nonhdfs/bin/coverage run test/runtests.py -v test/bin_test.py:LuigidTest'
nonhdfs runtests: commands[1] | coveralls
You have to provide either repo_token in .coveralls.yml, or launch via Travis
_________________________________________________________________________________________________________________________________________ summary _________________________________________________________________________________________________________________________________________
ERROR:   nonhdfs: commands failed
1
                                                                                                                                                                                                                                                                                           
~/spotify/repos/luigis/github_luigi fix-travis-false-positives*  
❯ export PYTHONPATH=''; tox -e nonhdfs test/bin_test.py:ServerTest; echo $?
nonhdfs develop-inst-noop: /home/arash/spotify/repos/luigis/github_luigi
nonhdfs runtests: PYTHONHASHSEED='2873888225'
nonhdfs runtests: commands[0] | coverage run test/runtests.py -v test/bin_test.py:ServerTest
test_404 (bin_test.ServerTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.106s

OK
nonhdfs runtests: commands[1] | coveralls
You have to provide either repo_token in .coveralls.yml, or launch via Travis
_________________________________________________________________________________________________________________________________________ summary _________________________________________________________________________________________________________________________________________
  nonhdfs: commands succeeded
  congratulations :)
0
```

**Comment by berkerpeksag** [comment]
> It's just that bin_test.py is magical or something.

The problem is in ServerTest. I've modified bin_test.py like this:

```py
import unittest
from server_test import ServerTest

class FooTest(unittest.TestCase):
    def test_bar(self):
        self.assertTrue(False)
```

When I run `tox -e nonhdfs test/bin_test.py`:

```
$ tox -e nonhdfs test/bin_test.py
nonhdfs develop-inst-nodeps: /home/berker/hacking/luigi
nonhdfs runtests: PYTHONHASHSEED='1795236263'
nonhdfs runtests: commands[0] | coverage run test/runtests.py -v test/bin_test.py
test_bar (bin_test.FooTest) ... FAIL
test_404 (bin_test.ServerTest) ... ok
test_api_404 (bin_test.ServerTest) ... ok
test_visualizer (bin_test.ServerTest) ... ok

======================================================================
FAIL: test_bar (bin_test.FooTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/berker/hacking/luigi/test/bin_test.py", line 26, in test_bar
    self.assertTrue(False)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 4 tests in 0.365s

FAILED (failures=1)
nonhdfs runtests: commands[1] | coveralls
You have to provide either repo_token in .coveralls.yml, or launch via Travis
  nonhdfs: commands succeeded
  congratulations :)
```

If I remove the ServerTest import, it works fine. It could be a test discovery or thread cleanup issue. I'll try to convert ServerTest to a mixin.

**Comment by berkerpeksag** [comment]
Same output without using nose:

```py
$ tox -e nonhdfs test.bin_test
nonhdfs develop-inst-nodeps: /home/berker/hacking/luigi
nonhdfs runtests: PYTHONHASHSEED='2386692542'
nonhdfs runtests: commands[0] | python -m unittest test.bin_test
FWARNING:tornado.access:404 GET /foo (127.0.0.1) 2.03ms
.WARNING:tornado.access:404 GET /api/foo (127.0.0.1) 1.15ms
..
======================================================================
FAIL: test_bar (test.bin_test.FooTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/bin_test.py", line 26, in test_bar
    self.assertTrue(False)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 4 tests in 0.350s

FAILED (failures=1)
WARNING:luigi.server:Failed saving scheduler state
Traceback (most recent call last):
  File "luigi/scheduler.py", line 242, in dump
    with open(self._state_path, 'w') as fobj:
IOError: [Errno 2] No such file or directory: '/var/lib/luigi-server/state.pickle'

  nonhdfs: commands succeeded
  congratulations :)
```

**Comment by berkerpeksag** [comment]
I've fixed the problem by using http://www.tornadoweb.org/en/stable/testing.html#tornado.testing.AsyncHTTPTestCase

But by using AsyncHTTPTestCase, bin_test is now redundant as it is. It should test bin/luigid CLI instead. We are using https://hg.python.org/cpython/file/default/Lib/test/test_tarfile.py#l1964 (e.g. run the CLI app in subrocess) to test command line interfaces in the Python project. I can update bin_test if your're OK with this approach.

Current server_test code is here: https://github.com/berkerpeksag/luigi/compare/spotify:master...berkerpeksag:server-tests

**Comment by erikbern** [comment]
So this was something I must have introduced in https://github.com/spotify/luigi/commit/d6e3ae019db7414945139e2ffd35dcf340784062 – Really sorry for that!

It would be awesome if we can merge your branch. Just send a PR.

How does it make bin_test redundant btw? We still want to test bin/luigid somehow

**Comment by berkerpeksag** [comment]
> How does it make bin_test redundant btw? We still want to test bin/luigid somehow

bin_test currently tests luigi.server.run directly, but testing luigi.server.run is hard, you need to mock pretty much everything. Since luigid is a command line application, we should test it in a more functional testing way(with more isolation). So currently, bin_test does not test anything with my patch. What I'm proposing is something like

```py
class CommandLineTestCase(unittest.TestCase):

    command = None

    def assertRunOK(self, *args):
        # subprocess boiler code
        stdout, stderr, returncode = subprocess.Popen(...)
        return stdout, returncode
```

then to test luigid, subclass it:

```py
class LuigidCommandLineTestCase(CommandLineTestCase):

    command = 'luigid'

    def test_port(self):
        stdout, returncode = self.assertRunOK('--port 9999')
        self.assertIn('fooo', stdout)
        self.assertEqual(returncode, 0)

    # test_deamon etc.
```

**Comment by berkerpeksag** [comment]
My patch needs a bit more work. rpc_test and probably other related tests are failing now. I have a question about rpc_test:

luigi.rpc.RemoteScheduler docstring says "Scheduler proxy object. Talks to a RemoteSchedulerResponder.", but since ace47a3bf1a70104db8336dac57a4250d3bfaf4d there is no *Responder class.

So do I really need to test RemoteScheduler directly, or instead can I create a dummy scheduler, and test RPC via testing the `/api/*` (RPCHandler in luigi/server.py to be exact) endpoint?

**Comment by erikbern** [comment]
Yes, the doc needs to be updated. Thanks for pointing out.

I think you could mock out the Scheduler, but it's probably easier to test it with a full fledged CentralPlannerScheduler.

**Comment by gpoulin** [comment]
I'm not sure it's relevant, but when I run the test on my local machine there is still a bunch of python processes that are running.
