### ISSUE TITLE
Backward incompatible changes in pipe_writer  in hdfs.py

### ISSUE THREAD

**Issue by Tarrasch** [spotify/luigi#791]
We got a stack trace like this:

```

> Runtime error:
> Traceback (most recent call last):
>   File "/usr/lib/python2.6/dist-packages/luigi/worker.py", line 164, in run
>     task_gen = self.task.run()
>   File "/usr/lib/python2.6/dist-packages/spotify_mq_pipeline/patching/album_subtype.py", line 69, in run
>     fout = output.open("w")
>   File "/usr/lib/python2.6/dist-packages/luigi/hdfs.py", line 837, in open
>     return self.format.pipe_writer(self.path)
>   File "/usr/lib/python2.6/dist-packages/spotify/luigi/hdfs.py", line 195, in hdfs_writer
>     return self.pipe_writer(hdfspipe)
>   File "/usr/lib/python2.6/dist-packages/spotify/luigi/hdfs.py", line 194, in hdfs_writer
>     hdfspipe = luigi.hdfs.HdfsAtomicWriteDirPipe(path, ".avro")
>   File "/usr/lib/python2.6/dist-packages/luigi/hdfs.py", line 729, in __init__
>     self.tmppath = tmppath(self.path)
>   File "/usr/lib/python2.6/dist-packages/luigi/hdfs.py", line 103, in tmppath
>     parsed = urlparse(path)
>   File "/usr/lib/python2.6/urlparse.py", line 129, in urlparse
>     tuple = urlsplit(url, scheme, allow_fragments)
>   File "/usr/lib/python2.6/urlparse.py", line 168, in urlsplit
>     i = url.find(':')
>   File "/usr/lib/python2.6/dist-packages/luigi/format.py", line 227, in __getattr__
>     return getattr(self._process.stdin, name)
> AttributeError: 'file' object has no attribute 'find'
```

Can https://github.com/spotify/luigi/commit/594246bff00339c77862a028c2110f37da7f88af and/or https://github.com/spotify/luigi/pull/769 be part of this. Can you take a quick glance @gpoulin? :)

**Comment by gpoulin** [comment]
Is it possible that the object at 
```pytb
File "/usr/lib/python2.6/dist-packages/spotify/luigi/hdfs.py", line 195, in hdfs_writer
     return self.pipe_writer(hdfspipe)
File "/usr/lib/python2.6/dist-packages/spotify/luigi/hdfs.py", line 194, in hdfs_writer
     hdfspipe = luigi.hdfs.HdfsAtomicWriteDirPipe(path, ".avro")
```

implements both pipe_writer and hdfs_writer? If it's the case it might have been cause by this 594246bff. Does #793 fix it? If not you can revert 594246b. It would probably break python3 hdfs but I'll figure out later. It's more important to keep stuffs working.

**Comment by gpoulin** [comment]
@Tarrasch #793 fixed it?

**Comment by Tarrasch** [comment]
Yes, Thanks @gpoulin !!! :)

By the way @gpoulin  and the rest of you guys. I'll be on vacation for 3 weeks now, so I won't be hanging around the repo and merging/commenting during that time. Happy hacking in the meantime! :)

**Comment by erikbern** [comment]
I'm going to rewrite Luigi in PHP until you get back

**Comment by gpoulin** [comment]
-_- ... I inherited of a data pipeline in PHP, it's not a wise idea ... `MySQL server has gone away`

**Comment by berkerpeksag** [comment]
I'd go with Python 1.6 instead :)
