### ISSUE TITLE
Failed to import 'db_task_history'

### ISSUE THREAD

**Issue by davidia** [spotify/luigi#919]
I tried enabling task history but it fails with:

    Traceback (most recent call last):
      File "/home/danderson/bin/luigid", line 9, in <module>
    load_entry_point('luigi==1.1.3', 'console_scripts', 'luigid')()
      File "/home/danderson/lib/python3.4/site-packages/luigi-1.1.3-py3.4.egg/luigi/cmdline.py", line 36, in luigid
    logdir=opts.logdir)
      File "/home/danderson/lib/python3.4/site-packages/luigi-1.1.3-py3.4.egg/luigi/process.py", line 117, in daemonize
    cmd(api_port=api_port, address=address)
      File "/home/danderson/lib/python3.4/site-packages/luigi-1.1.3-py3.4.egg/luigi/server.py", line 254, in run
    scheduler = CentralPlannerScheduler()
      File "/home/danderson/lib/python3.4/site-packages/luigi-1.1.3-py3.4.egg/luigi/scheduler.py", line 452, in __init__
    import db_task_history  # Needs sqlalchemy, thus imported here
    ImportError: No module named 'db_task_history'

I checked and db_task_history.py is where you would expect it to be

**Comment by gpoulin** [comment]
That's an issue with python3, I might have forget this import statement when I ported over to python3.

**Comment by davidia** [comment]
thank you!

**Comment by Tarrasch** [comment]
And thank you for reporting @davidia !
